// Cultural heritage hierarchy for search
export const CULTURAL_HIERARCHY: Record<string, string[]> = {
  Asian: [
    'East Asian',
    'Southeast Asian',
    'South Asian',
    'Central Asian',
    'Chinese',
    'Japanese',
    'Korean',
    'Taiwanese',
    'Vietnamese',
    'Filipino',
    'Malaysian',
    'Thai',
    'Indian',
    'Bengali',
    'Pakistani',
    'Uzbek',
  ],
  'East Asian': ['Chinese', 'Japanese', 'Korean', 'Taiwanese'],
  'Southeast Asian': ['Vietnamese', 'Filipino', 'Malaysian', 'Thai'],
  'South Asian': ['Indian', 'Bengali', 'Pakistani'],
  'Central Asian': ['Uzbek'],
  Americas: [
    'Latin American',
    'Caribbean',
    'North American',
    'Mexican',
    'Dominican',
    'Puerto Rican',
    'Salvadoran',
    'Jamaican',
    'Cajun/Creole',
    'Indigenous/Native American',
    'African American diaspora',
  ],
  'Latin American': ['Mexican', 'Dominican', 'Puerto Rican', 'Salvadoran'],
  Caribbean: ['Jamaican', 'Dominican', 'Puerto Rican'],
  'North American': ['Cajun/Creole', 'Indigenous/Native American', 'African American diaspora'],
  African: ['West African', 'Ethiopian', 'Nigerian'],
  European: [
    'Eastern European',
    'Mediterranean',
    'Italian',
    'Spanish',
    'Greek',
    'French',
    'Russian/Ukrainian',
    'Polish',
  ],
  Mediterranean: ['Italian', 'Spanish', 'Greek'],
  'Eastern European': ['Russian/Ukrainian', 'Polish'],
  'Middle Eastern': ['Levantine', 'Palestinian', 'Lebanese', 'Syrian', 'Jordanian', 'Israeli'],
  Levantine: ['Palestinian', 'Lebanese', 'Syrian', 'Jordanian'],
};

// Note: Option lists for filters have moved to `filterDefinitions.ts` (Phase 2B).
// CULTURAL_HIERARCHY is used by CulturalHeritageFilter and VirtualizedCulturalHeritageFilter.
