// AUTO-GENERATED by scripts/heritage/generate-heritage-hierarchy.ts — do not edit by hand
// Source of truth: data/vocab/cultural-heritage.vocab.json
// Ordering: vocab frequency DESC, then key ASC (siblings, at every level)
// Regenerate: npx tsx scripts/heritage/generate-heritage-hierarchy.ts

/**
 * Recursive nested option for the Cultural Heritage SEARCH filter. `value` is the
 * kebab vocab slug sent by the UI; `label` is the Title-Case display string;
 * `children` recurses for nested groups. Only the `top` + `sub` vocab tiers
 * appear here — `internal` nodes are hidden in the UI but still match via the
 * recursive DB expansion.
 */
export interface HeritageOption {
  value: string;
  label: string;
  children?: HeritageOption[];
}

export const culturalHeritageOptions: HeritageOption[] = [
  {
    value: 'americas',
    label: 'Americas',
    children: [
      {
        value: 'north-american',
        label: 'North American',
      },
      {
        value: 'latin-american',
        label: 'Latin American',
        children: [
          {
            value: 'mexican',
            label: 'Mexican',
          },
          {
            value: 'puerto-rican',
            label: 'Puerto Rican',
          },
        ],
      },
      {
        value: 'caribbean',
        label: 'Caribbean',
      },
    ],
  },
  {
    value: 'asian',
    label: 'Asian',
    children: [
      {
        value: 'east-asian',
        label: 'East Asian',
        children: [
          {
            value: 'chinese',
            label: 'Chinese',
          },
          {
            value: 'japanese',
            label: 'Japanese',
          },
          {
            value: 'korean',
            label: 'Korean',
          },
        ],
      },
      {
        value: 'south-asian',
        label: 'South Asian',
        children: [
          {
            value: 'indian',
            label: 'Indian',
          },
          {
            value: 'pakistani',
            label: 'Pakistani',
          },
        ],
      },
      {
        value: 'southeast-asian',
        label: 'Southeast Asian',
      },
      {
        value: 'central-asian',
        label: 'Central Asian',
        children: [
          {
            value: 'uzbek',
            label: 'Uzbek',
          },
        ],
      },
    ],
  },
  {
    value: 'indigenous-and-diaspora',
    label: 'Indigenous and Diaspora',
    children: [
      {
        value: 'african-american',
        label: 'African American',
      },
      {
        value: 'indigenous',
        label: 'Indigenous',
        children: [
          {
            value: 'lenape',
            label: 'Lenape',
          },
        ],
      },
    ],
  },
  {
    value: 'european',
    label: 'European',
    children: [
      {
        value: 'mediterranean',
        label: 'Mediterranean',
        children: [
          {
            value: 'italian',
            label: 'Italian',
          },
        ],
      },
      {
        value: 'eastern-european',
        label: 'Eastern European',
      },
    ],
  },
  {
    value: 'african',
    label: 'African',
    children: [
      {
        value: 'west-african',
        label: 'West African',
      },
      {
        value: 'north-african',
        label: 'North African',
      },
      {
        value: 'east-african',
        label: 'East African',
      },
    ],
  },
  {
    value: 'middle-eastern',
    label: 'Middle Eastern',
    children: [
      {
        value: 'levantine',
        label: 'Levantine',
      },
    ],
  },
];

/**
 * Flat option for the REVIEWER Cultural Heritage control. `value` is the Title-Case
 * label (the stored representation — a reviewer pick round-trips byte-identically
 * with `lessons.cultural_heritage`); `label` shows the full ancestor chain so the
 * flat control still reads hierarchically. Covers ALL 71 tiers incl. `internal`, so
 * closing the former free-text box invalidates nothing. See buildHeritageReviewOptions.
 */
export interface HeritageReviewOption {
  value: string;
  label: string;
}

export const culturalHeritageReviewOptions: HeritageReviewOption[] = [
  { value: 'Americas', label: 'Americas' },
  { value: 'North American', label: 'Americas → North American' },
  { value: 'Southern United States', label: 'Americas → North American → Southern United States' },
  { value: 'Latin American', label: 'Americas → Latin American' },
  { value: 'Mexican', label: 'Americas → Latin American → Mexican' },
  { value: 'Puerto Rican', label: 'Americas → Latin American → Puerto Rican' },
  { value: 'Honduran', label: 'Americas → Latin American → Honduran' },
  { value: 'Peruvian', label: 'Americas → Latin American → Peruvian' },
  { value: 'Salvadoran', label: 'Americas → Latin American → Salvadoran' },
  { value: 'Brazilian', label: 'Americas → Latin American → Brazilian' },
  { value: 'Ecuadorian', label: 'Americas → Latin American → Ecuadorian' },
  { value: 'Guyanese', label: 'Americas → Latin American → Guyanese' },
  { value: 'Dominican', label: 'Americas → Latin American → Dominican' },
  { value: 'Caribbean', label: 'Americas → Caribbean' },
  { value: 'Cuban', label: 'Americas → Caribbean → Cuban' },
  { value: 'Jamaican', label: 'Americas → Caribbean → Jamaican' },
  { value: 'Central American', label: 'Americas → Central American' },
  { value: 'South American', label: 'Americas → South American' },
  { value: 'Asian', label: 'Asian' },
  { value: 'East Asian', label: 'Asian → East Asian' },
  { value: 'Chinese', label: 'Asian → East Asian → Chinese' },
  { value: 'Japanese', label: 'Asian → East Asian → Japanese' },
  { value: 'Korean', label: 'Asian → East Asian → Korean' },
  { value: 'Taiwanese', label: 'Asian → East Asian → Taiwanese' },
  { value: 'South Asian', label: 'Asian → South Asian' },
  { value: 'Indian', label: 'Asian → South Asian → Indian' },
  { value: 'Pakistani', label: 'Asian → South Asian → Pakistani' },
  { value: 'Sri Lankan', label: 'Asian → South Asian → Sri Lankan' },
  { value: 'Southeast Asian', label: 'Asian → Southeast Asian' },
  { value: 'Vietnamese', label: 'Asian → Southeast Asian → Vietnamese' },
  { value: 'Malaysian', label: 'Asian → Southeast Asian → Malaysian' },
  { value: 'Central Asian', label: 'Asian → Central Asian' },
  { value: 'Uzbek', label: 'Asian → Central Asian → Uzbek' },
  { value: 'Indigenous and Diaspora', label: 'Indigenous and Diaspora' },
  { value: 'African American', label: 'Indigenous and Diaspora → African American' },
  {
    value: 'Black culinary history',
    label: 'Indigenous and Diaspora → African American → Black culinary history',
  },
  { value: 'Soul Food', label: 'Indigenous and Diaspora → African American → Soul Food' },
  { value: 'Indigenous', label: 'Indigenous and Diaspora → Indigenous' },
  { value: 'Lenape', label: 'Indigenous and Diaspora → Indigenous → Lenape' },
  { value: 'Haudenosaunee', label: 'Indigenous and Diaspora → Indigenous → Haudenosaunee' },
  {
    value: 'Three Sisters traditions',
    label: 'Indigenous and Diaspora → Indigenous → Three Sisters traditions',
  },
  { value: 'Cajun/Creole', label: 'Indigenous and Diaspora → Cajun/Creole' },
  { value: 'European', label: 'European' },
  { value: 'Mediterranean', label: 'European → Mediterranean' },
  { value: 'Italian', label: 'European → Mediterranean → Italian' },
  { value: 'Spanish', label: 'European → Mediterranean → Spanish' },
  { value: 'Greek', label: 'European → Mediterranean → Greek' },
  { value: 'Eastern European', label: 'European → Eastern European' },
  { value: 'Ukrainian', label: 'European → Eastern European → Ukrainian' },
  { value: 'Russian', label: 'European → Eastern European → Russian' },
  { value: 'Polish', label: 'European → Eastern European → Polish' },
  { value: 'Irish', label: 'European → Irish' },
  { value: 'French', label: 'European → French' },
  { value: 'African', label: 'African' },
  { value: 'West African', label: 'African → West African' },
  { value: 'Nigerian', label: 'African → West African → Nigerian' },
  { value: 'North African', label: 'African → North African' },
  { value: 'Egyptian', label: 'African → North African → Egyptian' },
  { value: 'Moroccan', label: 'African → North African → Moroccan' },
  { value: 'East African', label: 'African → East African' },
  { value: 'Kenyan', label: 'African → East African → Kenyan' },
  { value: 'Ethiopian', label: 'African → East African → Ethiopian' },
  { value: 'Middle Eastern', label: 'Middle Eastern' },
  { value: 'Levantine', label: 'Middle Eastern → Levantine' },
  { value: 'Palestinian', label: 'Middle Eastern → Levantine → Palestinian' },
  { value: 'Jordanian', label: 'Middle Eastern → Levantine → Jordanian' },
  { value: 'Lebanese', label: 'Middle Eastern → Levantine → Lebanese' },
  { value: 'Syrian', label: 'Middle Eastern → Levantine → Syrian' },
  { value: 'Yemeni', label: 'Middle Eastern → Yemeni' },
  { value: 'Israeli', label: 'Middle Eastern → Israeli' },
  { value: 'Persian', label: 'Middle Eastern → Persian' },
];

/**
 * The CLOSED set of Cultural Heritage values a reviewer may save — the `value`s of
 * culturalHeritageReviewOptions, same order. Consumed by `CulturalHeritageEnum` in
 * src/types/lessonMetadata.zod.ts (and hand-mirrored in the edge module
 * supabase/functions/_shared/metadataSchemas.ts; the equivalence test guards drift).
 * There is NO reviewer free-text path: to add a value, add it to
 * data/vocab/cultural-heritage.vocab.json and regenerate (ask the maintainer).
 */
export const CULTURAL_HERITAGE_VALUES = [
  'Americas',
  'North American',
  'Southern United States',
  'Latin American',
  'Mexican',
  'Puerto Rican',
  'Honduran',
  'Peruvian',
  'Salvadoran',
  'Brazilian',
  'Ecuadorian',
  'Guyanese',
  'Dominican',
  'Caribbean',
  'Cuban',
  'Jamaican',
  'Central American',
  'South American',
  'Asian',
  'East Asian',
  'Chinese',
  'Japanese',
  'Korean',
  'Taiwanese',
  'South Asian',
  'Indian',
  'Pakistani',
  'Sri Lankan',
  'Southeast Asian',
  'Vietnamese',
  'Malaysian',
  'Central Asian',
  'Uzbek',
  'Indigenous and Diaspora',
  'African American',
  'Black culinary history',
  'Soul Food',
  'Indigenous',
  'Lenape',
  'Haudenosaunee',
  'Three Sisters traditions',
  'Cajun/Creole',
  'European',
  'Mediterranean',
  'Italian',
  'Spanish',
  'Greek',
  'Eastern European',
  'Ukrainian',
  'Russian',
  'Polish',
  'Irish',
  'French',
  'African',
  'West African',
  'Nigerian',
  'North African',
  'Egyptian',
  'Moroccan',
  'East African',
  'Kenyan',
  'Ethiopian',
  'Middle Eastern',
  'Levantine',
  'Palestinian',
  'Jordanian',
  'Lebanese',
  'Syrian',
  'Yemeni',
  'Israeli',
  'Persian',
] as const;
