// AUTO-GENERATED by scripts/heritage/generate-heritage-hierarchy.ts — do not edit by hand
// Source of truth: data/vocab/cultural-heritage.vocab.json
// Ordering: vocab frequency DESC, then key ASC (siblings, at every level)
// Regenerate: npx tsx scripts/heritage/generate-heritage-hierarchy.ts

/**
 * Recursive nested option for the Cultural Heritage filter. `value` is the
 * kebab vocab slug sent by the UI; `label` is the Title-Case display string;
 * `children` recurses for nested groups. Only the `top` + `sub` vocab tiers
 * appear here — `internal` nodes are hidden in the UI but still match via the
 * recursive DB expansion.
 */
export interface HeritageOption {
  value: string;
  label: string;
  children?: HeritageOption[];
}

export const culturalHeritageOptions: HeritageOption[] = [
  {
    value: 'americas',
    label: 'Americas',
    children: [
      {
        value: 'north-american',
        label: 'North American',
      },
      {
        value: 'latin-american',
        label: 'Latin American',
        children: [
          {
            value: 'mexican',
            label: 'Mexican',
          },
          {
            value: 'puerto-rican',
            label: 'Puerto Rican',
          },
        ],
      },
      {
        value: 'caribbean',
        label: 'Caribbean',
      },
    ],
  },
  {
    value: 'asian',
    label: 'Asian',
    children: [
      {
        value: 'east-asian',
        label: 'East Asian',
        children: [
          {
            value: 'chinese',
            label: 'Chinese',
          },
          {
            value: 'japanese',
            label: 'Japanese',
          },
          {
            value: 'korean',
            label: 'Korean',
          },
        ],
      },
      {
        value: 'south-asian',
        label: 'South Asian',
        children: [
          {
            value: 'indian',
            label: 'Indian',
          },
          {
            value: 'pakistani',
            label: 'Pakistani',
          },
        ],
      },
      {
        value: 'southeast-asian',
        label: 'Southeast Asian',
      },
      {
        value: 'central-asian',
        label: 'Central Asian',
        children: [
          {
            value: 'uzbek',
            label: 'Uzbek',
          },
        ],
      },
    ],
  },
  {
    value: 'indigenous-and-diaspora',
    label: 'Indigenous and Diaspora',
    children: [
      {
        value: 'african-american',
        label: 'African American',
      },
      {
        value: 'indigenous',
        label: 'Indigenous',
        children: [
          {
            value: 'lenape',
            label: 'Lenape',
          },
        ],
      },
    ],
  },
  {
    value: 'european',
    label: 'European',
    children: [
      {
        value: 'mediterranean',
        label: 'Mediterranean',
        children: [
          {
            value: 'italian',
            label: 'Italian',
          },
        ],
      },
      {
        value: 'eastern-european',
        label: 'Eastern European',
      },
    ],
  },
  {
    value: 'african',
    label: 'African',
    children: [
      {
        value: 'west-african',
        label: 'West African',
      },
      {
        value: 'north-african',
        label: 'North African',
      },
      {
        value: 'east-african',
        label: 'East African',
      },
    ],
  },
  {
    value: 'middle-eastern',
    label: 'Middle Eastern',
    children: [
      {
        value: 'levantine',
        label: 'Levantine',
      },
    ],
  },
];
