#!/usr/bin/env python3
"""
Generate the PR 5a heritage-canonicalization migration SQL from the
committed vocabulary artifact.

Input:  data/vocab/cultural-heritage.vocab.json (emitted by
        scripts/parse-heritage-worksheet.py --emit-json)
Output: full migration SQL on stdout — redirect into
        supabase/migrations/<datestamp>_pr5a_heritage_canonicalization.sql
        and commit the result. The mapping VALUES list is never hand-typed.

The rewrite maps each cultural_heritage array element through the artifact's
non-identity alias pairs (alias literal → canonical SURFACE LABEL, the stored
Title Case form — not the kebab canonical key), dedupes preserving
first-occurrence order, and only touches live rows (retired_at IS NULL) that
contain at least one alias. lessons_normalize_write §J mirrors the column
into metadata->'culturalHeritage' (column wins);
update_lesson_search_vector_trigger refreshes FTS (UPDATE OF
cultural_heritage). Idempotent: canonical values map to themselves, so a
re-run matches zero rows.

Self-checks (fail loudly, no silent emit): every alias target key resolves
to a canonical entry; every RHS is a canonical surface label distinct from
its LHS; pair count matches the heritage worksheet expectation (17 = 13
kebab drift literals + 4 semantic merges).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT_PATH = REPO_ROOT / "data" / "vocab" / "cultural-heritage.vocab.json"

EXPECTED_NON_IDENTITY_PAIRS = 17


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_pairs(artifact: dict) -> list[tuple[str, str]]:
    """Non-identity (alias literal → canonical surface label) pairs."""
    errors: list[str] = []
    label_by_key = {c["key"]: c["label"] for c in artifact["canonical"]}

    pairs: list[tuple[str, str]] = []
    for literal, target_key in sorted(artifact["alias_map"].items()):
        label = label_by_key.get(target_key)
        if label is None:
            errors.append(
                f"alias {literal!r}: target key {target_key!r} has no canonical entry"
            )
            continue
        if literal == label:
            continue  # identity — canonical literal confirming itself
        pairs.append((literal, label))

    canonical_labels = set(label_by_key.values())
    for literal, label in pairs:
        if label not in canonical_labels:
            errors.append(f"pair RHS {label!r} is not a canonical surface label")

    if len(pairs) != EXPECTED_NON_IDENTITY_PAIRS:
        errors.append(
            f"expected {EXPECTED_NON_IDENTITY_PAIRS} non-identity pairs,"
            f" found {len(pairs)}: {[p[0] for p in pairs]}"
        )

    if errors:
        raise ValueError("\n".join(errors))
    return pairs


def render_values(pairs: list[tuple[str, str]], indent: str) -> str:
    return (",\n" + indent).join(
        f"({sql_quote(alias)}, {sql_quote(canonical)})" for alias, canonical in pairs
    )


def render_in_list(literals: list[str], indent: str) -> str:
    lines: list[str] = []
    line: list[str] = []
    for lit in literals:
        line.append(sql_quote(lit))
        if len(line) == 4:
            lines.append(", ".join(line))
            line = []
    if line:
        lines.append(", ".join(line))
    return (",\n" + indent).join(lines)


def main() -> int:
    artifact = json.loads(ARTIFACT_PATH.read_text(encoding="utf-8"))
    try:
        pairs = build_pairs(artifact)
    except ValueError as exc:
        print(f"GENERATOR SELF-CHECK FAILURE:\n{exc}", file=sys.stderr)
        return 1

    values_8 = render_values(pairs, " " * 8)
    values_4 = render_values(pairs, " " * 4)
    aliases_in_8 = render_in_list([p[0] for p in pairs], " " * 8)
    provenance = artifact["provenance"]

    print(f"""\
-- =====================================================
-- Migration: pr5a_heritage_canonicalization
-- =====================================================
-- GENERATED by scripts/generate-heritage-rewrite-migration.py from
-- data/vocab/cultural-heritage.vocab.json — regenerate, don't hand-edit.
--   artifact source: {provenance["source"]}
--   artifact source_commit: {provenance["source_commit"]}
--   artifact emitted: {provenance["emitted"]}
--
-- Description: Rewrite every live lessons.cultural_heritage value to its
-- Stage-1-locked canonical Title Case surface label (PR 5a — D4 vocabulary
-- canonicalization, heritage rehearsal). {len(pairs)} non-identity rewrites:
-- 13 kebab drift literals + 4 semantic merges (Native American /
-- Indigenous/Native American / Indigenous Peoples → Indigenous;
-- African American diaspora → African American).
--
-- Mechanism notes (design doc 2026-06-11-…-pr5-canonicalization-design.md §4):
--   * Writes the cultural_heritage COLUMN only. lessons_normalize_write §J
--     mirrors the column into metadata->'culturalHeritage' in the same
--     statement (column wins on disagreement, 20260518000000).
--   * update_lesson_search_vector_trigger (UPDATE OF cultural_heritage,
--     20260521000000) regenerates search_vector row-by-row.
--   * Live rows only (retired_at IS NULL) — the 21 soft-retired imports
--     keep their archival vocabulary (user decision 2026-06-11).
--   * Idempotent: canonical labels are not in the alias list, so re-running
--     the UPDATE matches zero rows; the snapshot INSERT is ON CONFLICT
--     DO NOTHING, so re-runs never overwrite original pre-rewrite values.

-- =====================================================
-- (1) Rollback snapshot — original values of every row the rewrite touches
-- =====================================================

CREATE TABLE IF NOT EXISTS public.pr5a_heritage_rollback (
  lesson_id text PRIMARY KEY,
  cultural_heritage text[],
  metadata_culturalheritage jsonb
);

-- Service-role-only: RLS enabled with NO policies.
ALTER TABLE public.pr5a_heritage_rollback ENABLE ROW LEVEL SECURITY;

INSERT INTO public.pr5a_heritage_rollback (lesson_id, cultural_heritage, metadata_culturalheritage)
SELECT l.lesson_id, l.cultural_heritage, l.metadata->'culturalHeritage'
FROM public.lessons l
WHERE l.retired_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM unnest(l.cultural_heritage) v
    JOIN (VALUES
        {values_8}
    ) m(alias, canonical) ON v = m.alias
  )
ON CONFLICT (lesson_id) DO NOTHING;

-- =====================================================
-- (2) Rewrite: map aliases → canonical surface labels, dedupe preserving
--     first-occurrence order
-- =====================================================

WITH alias_map(alias, canonical) AS (
  VALUES
    {values_4}
)
UPDATE public.lessons l
SET cultural_heritage = (
  SELECT array_agg(val ORDER BY first_ord)
  FROM (
    SELECT COALESCE(m.canonical, u.val) AS val, min(u.ord) AS first_ord
    FROM unnest(l.cultural_heritage) WITH ORDINALITY u(val, ord)
    LEFT JOIN alias_map m ON m.alias = u.val
    GROUP BY COALESCE(m.canonical, u.val)
  ) mapped
)
WHERE l.retired_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM unnest(l.cultural_heritage) v
    JOIN alias_map m ON v = m.alias
  );

-- =====================================================
-- (3) Post-verify: no alias literal survives on any live row
--     (column AND metadata mirror)
-- =====================================================

DO $$
DECLARE
  v_aliases CONSTANT text[] := ARRAY[
        {aliases_in_8}
  ];
  v_column_rows integer;
  v_metadata_rows integer;
BEGIN
  SELECT count(*) INTO v_column_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND l.cultural_heritage && v_aliases;

  SELECT count(*) INTO v_metadata_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND jsonb_typeof(l.metadata->'culturalHeritage') = 'array'
    AND EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(l.metadata->'culturalHeritage') mv
      WHERE mv = ANY (v_aliases)
    );

  IF v_column_rows > 0 OR v_metadata_rows > 0 THEN
    RAISE EXCEPTION
      'pr5a heritage canonicalization failed post-verify: % live rows with alias in column, % in metadata mirror',
      v_column_rows, v_metadata_rows;
  END IF;
END $$;

-- =====================================================
-- ROLLBACK (keep as comments)
-- =====================================================
-- Restore is a FORWARD migration reading the snapshot table. Restoring the
-- column is sufficient: lessons_normalize_write §J re-mirrors metadata from
-- the column (column wins), and the FTS trigger refreshes search_vector
-- (UPDATE OF cultural_heritage).
--
-- UPDATE public.lessons l
-- SET cultural_heritage = r.cultural_heritage
-- FROM public.pr5a_heritage_rollback r
-- WHERE l.lesson_id = r.lesson_id;
--
-- pr5a_heritage_rollback is dropped by a cleanup migration after PR 6 ships:
-- DROP TABLE IF EXISTS public.pr5a_heritage_rollback;\
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
