-- AUTO-GENERATED by scripts/heritage/generate-heritage-hierarchy.ts — do not edit by hand
-- Source of truth: data/vocab/cultural-heritage.vocab.json
-- Inert seed fragment for cultural_heritage_hierarchy (key, label, parent_key).
-- ALL tiers (top + sub + internal) are present: internal nodes are hidden in
-- the UI but MUST live in the table so the recursive expand_cultural_heritage
-- walk can match them. This file is folded into the C1.2 migration; C1.1
-- itself performs NO database writes.
-- Ordering: TOPOLOGICAL — depth ASC (roots first, so every parent row precedes
-- its children), then vocab frequency DESC, then key ASC within each depth band.
-- A single multi-row INSERT satisfies the self-referential FK at statement-end
-- regardless of row order; parents-before-children is used for readability and
-- robustness (safe even if the INSERT is ever split). This is INTENTIONALLY a
-- different ordering than the UI options artifact, which is frequency-DESC for
-- display.

INSERT INTO cultural_heritage_hierarchy (key, label, parent_key) VALUES
  ('americas', 'Americas', NULL),
  ('asian', 'Asian', NULL),
  ('indigenous-and-diaspora', 'Indigenous and Diaspora', NULL),
  ('european', 'European', NULL),
  ('african', 'African', NULL),
  ('middle-eastern', 'Middle Eastern', NULL),
  ('north-american', 'North American', 'americas'),
  ('latin-american', 'Latin American', 'americas'),
  ('mediterranean', 'Mediterranean', 'european'),
  ('east-asian', 'East Asian', 'asian'),
  ('african-american', 'African American', 'indigenous-and-diaspora'),
  ('indigenous', 'Indigenous', 'indigenous-and-diaspora'),
  ('caribbean', 'Caribbean', 'americas'),
  ('south-asian', 'South Asian', 'asian'),
  ('west-african', 'West African', 'african'),
  ('levantine', 'Levantine', 'middle-eastern'),
  ('southeast-asian', 'Southeast Asian', 'asian'),
  ('central-asian', 'Central Asian', 'asian'),
  ('eastern-european', 'Eastern European', 'european'),
  ('yemeni', 'Yemeni', 'middle-eastern'),
  ('irish', 'Irish', 'european'),
  ('north-african', 'North African', 'african'),
  ('central-american', 'Central American', 'americas'),
  ('east-african', 'East African', 'african'),
  ('israeli', 'Israeli', 'middle-eastern'),
  ('persian', 'Persian', 'middle-eastern'),
  ('south-american', 'South American', 'americas'),
  ('cajun-creole', 'Cajun/Creole', 'indigenous-and-diaspora'),
  ('french', 'French', 'european'),
  ('mexican', 'Mexican', 'latin-american'),
  ('italian', 'Italian', 'mediterranean'),
  ('chinese', 'Chinese', 'east-asian'),
  ('japanese', 'Japanese', 'east-asian'),
  ('indian', 'Indian', 'south-asian'),
  ('lenape', 'Lenape', 'indigenous'),
  ('spanish', 'Spanish', 'mediterranean'),
  ('pakistani', 'Pakistani', 'south-asian'),
  ('puerto-rican', 'Puerto Rican', 'latin-american'),
  ('uzbek', 'Uzbek', 'central-asian'),
  ('haudenosaunee', 'Haudenosaunee', 'indigenous'),
  ('korean', 'Korean', 'east-asian'),
  ('ukrainian', 'Ukrainian', 'eastern-european'),
  ('cuban', 'Cuban', 'caribbean'),
  ('egyptian', 'Egyptian', 'north-african'),
  ('greek', 'Greek', 'mediterranean'),
  ('honduran', 'Honduran', 'latin-american'),
  ('jamaican', 'Jamaican', 'caribbean'),
  ('kenyan', 'Kenyan', 'east-african'),
  ('nigerian', 'Nigerian', 'west-african'),
  ('peruvian', 'Peruvian', 'latin-american'),
  ('salvadoran', 'Salvadoran', 'latin-american'),
  ('vietnamese', 'Vietnamese', 'southeast-asian'),
  ('brazilian', 'Brazilian', 'latin-american'),
  ('ecuadorian', 'Ecuadorian', 'latin-american'),
  ('ethiopian', 'Ethiopian', 'east-african'),
  ('guyanese', 'Guyanese', 'latin-american'),
  ('malaysian', 'Malaysian', 'southeast-asian'),
  ('moroccan', 'Moroccan', 'north-african'),
  ('palestinian', 'Palestinian', 'levantine'),
  ('russian', 'Russian', 'eastern-european'),
  ('southern-united-states', 'Southern United States', 'north-american'),
  ('sri-lankan', 'Sri Lankan', 'south-asian'),
  ('taiwanese', 'Taiwanese', 'east-asian'),
  ('black-culinary-history', 'Black culinary history', 'african-american'),
  ('dominican', 'Dominican', 'latin-american'),
  ('jordanian', 'Jordanian', 'levantine'),
  ('lebanese', 'Lebanese', 'levantine'),
  ('polish', 'Polish', 'eastern-european'),
  ('soul-food', 'Soul Food', 'african-american'),
  ('syrian', 'Syrian', 'levantine'),
  ('three-sisters-traditions', 'Three Sisters traditions', 'indigenous');
