-- =====================================================
-- Migration: 20260702160000_t4_dedup_retire.sql
-- =====================================================
-- T4c — soft-retire 61 user-approved duplicate lessons (go-live sprint).
--
-- Source of truth: docs/plans/t4-dedup/decisions.json (the T4 walkthrough
-- artifact — every verdict user-confirmed live 2026-07-02). This file is
-- GENERATED by scripts/dedup-sweep/generate-retire-migration.mjs; DO NOT
-- hand-edit — re-run the generator to regenerate. No lesson_id is hand-typed.
--
-- 61 lessons across 57 groups (39 retire_duplicate + 18 keep_family
-- with an embedded exact-copy pair). 250 named survivors stay live.
--
-- Mechanism (design decision D5): SOFT-retire only — never DELETE. Sets
-- retired_at = now() and retired_reason = 'dedup:<group_id>' on the losers.
-- The retired_at / retired_reason columns already exist (added by the imports
-- cleanup, 20260520000000). search_lessons + the search view already filter
-- retired_at IS NULL, so retired rows drop out of public search but stay
-- linkable by direct id via lessons_with_metadata (20260520030000). Survivors
-- are untouched — no metadata blending/merging.
--
-- Rollback: sibling 20260702160000_t4_dedup_retire.sql.rollback restores retired_at /
-- retired_reason for exactly these 61 ids from the snapshot table below.
-- The snapshot table public.t4_dedup_retire_rollback is LEFT IN PLACE as the
-- recovery artifact (a post-launch cleanup migration drops it once PROD-stable).
--
-- PROD pre-registered state (read-only probe 2026-07-02): live corpus 764,
-- all 61 present + live + none already retired → post-apply live corpus 703.
-- TEST may hold fewer than 61 of these ids; the in-migration asserts below are
-- written to hold for "all targets present in THIS db", not a hard 61 — the
-- exact-61 check is a PROD-only environment verification (see the brief).

-- =====================================================
-- (1) Rollback snapshot table (service-role only: RLS on, NO policies —
--     mirrors the c02_retag_rollback / wave4 snapshot precedent).
-- =====================================================
CREATE TABLE IF NOT EXISTS public.t4_dedup_retire_rollback (
  lesson_id            text PRIMARY KEY,
  prior_retired_at     timestamptz,
  prior_retired_reason text,
  group_id             text NOT NULL,
  snapshotted_at       timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.t4_dedup_retire_rollback ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- (2) Compile-time guard — the embedded target list is exactly 61 distinct ids.
--     (A property of THIS file, independent of DB contents.)
-- =====================================================
DO $$
DECLARE
  n_total    int;
  n_distinct int;
BEGIN
  SELECT count(*), count(DISTINCT id)
    INTO n_total, n_distinct
  FROM unnest(ARRAY[
      '1sKR57WGb9pviOroK2xzmLz9ro6S3w9oAg_oVByk76DM',
      '19Tg4I9XywohpcrdBZ77vaBgyIdYhxGo0bk3FpSUcE2Y',
      '1Hrjix7fb6KQEVKwegeWLkoiUx8fIWpO1UBKEU0ni2QU',
      'lesson_2004c1a511fe41b58e58f1aefd339773',
      'lesson_78fb31393f1e4d629bfdf735ebd97694',
      '1WKXLADkrfgZ7462f3JKfHNV-trHtuNtmo3i6Gq-PqeA',
      'lesson_2d43fc766fa14401b48065f167003ded',
      'lesson_6c695009089f41f99432563f09f57f40',
      '1cOoL_f4KW083IAnhyCyo0RUXNXnZQ-LvhShNpuD917k',
      'lesson_9d3fa2495f2f41bd9946eec528198210',
      '1YeRlyncgM-gMS-Aica2Fk7wjBsRN9-K6',
      '1vDebvrcoPdDcoooLnpF64P3ade4l8ZRqVkfSlEAyYts',
      'lesson_d5c52872fd214f289d3cafaf0af3e607',
      'lesson_727ff8bd39e44c7eaa1439302f02c93a',
      'lesson_d4a676556c8d4c03bbc142d0f89c0010',
      'lesson_d28f99cce1784da08593876f227338ed',
      '1z6FCSrVdvFhcui0UKoJMPw5vwfy9iHUd2hC67bEhE5o',
      'lesson_a2c4451732bd464281dfa8f7efd4d464',
      'lesson_5bb0699f088d4b6cb0bac14b4477e259',
      '13nUlv33cUEy2yjjzCARmrlCIHO4oDwQxyCNHVyUtKGk',
      '16evw1D1b7oSDzm-vyvk2yXaIAt9XEwYsoWUjWE0CgpY',
      'lesson_cd3c5ef4e6e848fd9b062d47c382ae5e',
      '12yRCn3m298kp_ID-baEGYsHYP48f2zfFrGYbFnzdpLM',
      'lesson_adfac505fafc4a6ebfe1533b355ed154',
      '13jE3-XsWBgxZpiSFB0MDFxur3HGv_zAxqzstYDhhuaI',
      '1Vq5KMCGiH_PxhZ88tyRrgnxUChgiNd75El49aimP4yQ',
      '12eCbV1wJMk_qL3DPKY3qaR_q_eu7CpojLr0tmJXHm5k',
      '1NpJLjpNVppJXHvGcC_W8c4Wwt5UhJA6KizI6QJtKZFg',
      '1vnOYmF90vIaodnDkjLtXQdSLoLdE38HALLK8OfcwntM',
      '1CE324nZDL2kz_4P5TwDuvoX7Zx_NMwUz',
      '1g1_hRDipt9_3YcSS2hka46gNwsuVo1sd',
      '1_ZSnx9J--WJCTJEp3YzqOly1axW_65nY',
      '1tU6lE36cuzrNIFb4jKLB2hLA4mAY9j7xWBH9jOHhuW0',
      'lesson_bf1f76835a7446f78bfa843b7cbb99dd',
      '181lWTGhtMXpO95d3JOAiPYXQe963z_Ru5Ibpvc9kbrE',
      'lesson_d4dda9480bc14c658352e00a2a49d02c',
      'lesson_4d119999d8d54a828d9cb217f6d98613',
      'lesson_47fca82c179549c2919a6eb283357b58',
      '16mykieJMT9T8b1iKHErAUFRhC-Sou_FckP-CzyJIOG4',
      '1iKSljm8MfixYb1HI9OgTKka-fBf9uln_',
      '0BwC8Pf3ZwAXjNnhsOUZNLVRIUE0',
      '1tVWgHidAxvsPRMW2aJXd6YcFP9w0kbK6uOj_nbpu-KM',
      '18aRAD5iY1YxcaqTUZBhflNDAstEAHumK',
      '1l7A2jTOeXN5rV-dOhb6eH59URYlCYK8BF8K-xsd_ut8',
      'lesson_c78f6845475d4956bb9a038448bfea0c',
      'lesson_e7dbdb5dc324470392f1b761eb62fac8',
      'lesson_8be5b41f08bd43a99ac8cb113cc6dbd0',
      '1cwCnyYH_67kVHNbgkbcP0UmGn7vjRenOyndkaR1r1SU',
      '1ov2wUSmaHCy8CwpBt_T6ADqB5jo6QC2IzhqlFBrzYNw',
      '1zYSlW4BcZajmrZMuhUiRt6zd7hpQWdDFr4SMCuEhG48',
      '1vlKyiIiQPjoJ3Ek790STQlN9Ie87bYNbENpPa52S8Bg',
      '1J2HY5aTORYqL2MLI96g-357msUdFSq82SlqE2PHsUl4',
      '1UCyriRP14jUWMetMP6Olivo6XTS3COl14Et8dtpmkPs',
      '1T1sgLmsWzEYkAXNvsX4NMitYf0Au9o0Y8QZEsXpcPSo',
      '1730LjSjM6rScDdd0uqVm1JHFsiomc3yi',
      '1JRUHeRL6Ttr5hGyvdU-a5uqsjZC7fBWx',
      '1sMS_PNeRlanHoPh6iQDCJ4wVcQ5HPsrP',
      'lesson_7f6a2a772f044c0c87f98f9cde200320',
      '1xdz4aJqRcHYaAluj-x3C0VoQRM3UNy-gERUvpuOuwcM',
      '1cS3llhLF1k2bwgwz1f62fWk938evVGRE9crGuAWT3_g',
      '1JEpJpbINYmbIN9j5W2dYrgIW6e0EqpalMa3kqm_53cI'
    ]::text[]) AS id;
  IF n_total <> 61 OR n_distinct <> 61 THEN
    RAISE EXCEPTION 't4c ABORT: embedded target list is % rows / % distinct (expected 61/61)',
      n_total, n_distinct;
  END IF;
END $$;

-- =====================================================
-- (3) Snapshot the CURRENT state of every present target BEFORE the update.
--     INNER JOIN → only rows that actually exist in THIS db are snapshotted
--     (matches the precedent; on TEST that may be < 61).
-- =====================================================
INSERT INTO public.t4_dedup_retire_rollback (lesson_id, prior_retired_at, prior_retired_reason, group_id)
SELECT v.lesson_id, l.retired_at, l.retired_reason, v.group_id
FROM (VALUES
  ('anywhere-farm-30bddc', '1sKR57WGb9pviOroK2xzmLz9ro6S3w9oAg_oVByk76DM'),
  ('legend-of-the-3-sisters-eff077', '19Tg4I9XywohpcrdBZ77vaBgyIdYhxGo0bk3FpSUcE2Y'),
  ('november-will-it-decompose-part-ii-4ab586', '1Hrjix7fb6KQEVKwegeWLkoiUx8fIWpO1UBKEU0ni2QU'),
  ('worm-study-65ab90', 'lesson_2004c1a511fe41b58e58f1aefd339773'),
  ('potato-exploration-9223aa', 'lesson_78fb31393f1e4d629bfdf735ebd97694'),
  ('butterflies-f3d4b7', '1WKXLADkrfgZ7462f3JKfHNV-trHtuNtmo3i6Gq-PqeA'),
  ('the-apple-story-4c02c3', 'lesson_2d43fc766fa14401b48065f167003ded'),
  ('garden-jobs-afbe9e', 'lesson_6c695009089f41f99432563f09f57f40'),
  ('insect-detectives-2e1a88', '1cOoL_f4KW083IAnhyCyo0RUXNXnZQ-LvhShNpuD917k'),
  ('worm-breakfast-4606c3', 'lesson_9d3fa2495f2f41bd9946eec528198210'),
  ('fattoush-8c6942', '1YeRlyncgM-gMS-Aica2Fk7wjBsRN9-K6'),
  ('fattoush-8c6942', '1vDebvrcoPdDcoooLnpF64P3ade4l8ZRqVkfSlEAyYts'),
  ('sun-printing-ac6918', 'lesson_d5c52872fd214f289d3cafaf0af3e607'),
  ('the-garden-in-the-fall-ccb9af', 'lesson_727ff8bd39e44c7eaa1439302f02c93a'),
  ('the-garden-in-the-fall-ccb9af', 'lesson_d4a676556c8d4c03bbc142d0f89c0010'),
  ('vegetable-ramen-c0f2e8', 'lesson_d28f99cce1784da08593876f227338ed'),
  ('hispanic-heritage-month-baleadas-71a886', '1z6FCSrVdvFhcui0UKoJMPw5vwfy9iHUd2hC67bEhE5o'),
  ('baking-intro-pumpkin-muffins-ad6860', 'lesson_a2c4451732bd464281dfa8f7efd4d464'),
  ('plant-life-cycle-exploration-3e68f8', 'lesson_5bb0699f088d4b6cb0bac14b4477e259'),
  ('chilled-cucumber-and-tahini-soup-with-sp-8090b5', '13nUlv33cUEy2yjjzCARmrlCIHO4oDwQxyCNHVyUtKGk'),
  ('empanadas-corn-salad-eadd2e', '16evw1D1b7oSDzm-vyvk2yXaIAt9XEwYsoWUjWE0CgpY'),
  ('welcome-garden-exploration-gardening-for-4f26ca', 'lesson_cd3c5ef4e6e848fd9b062d47c382ae5e'),
  ('berry-rosehip-bars-abcddb', '12yRCn3m298kp_ID-baEGYsHYP48f2zfFrGYbFnzdpLM'),
  ('who-lives-in-the-garden-9793a2', 'lesson_adfac505fafc4a6ebfe1533b355ed154'),
  ('mural-painting-101-beautifying-the-garde-f10d4b', '13jE3-XsWBgxZpiSFB0MDFxur3HGv_zAxqzstYDhhuaI'),
  ('three-sisters-and-companion-planting-a-s-855f46', '1Vq5KMCGiH_PxhZ88tyRrgnxUChgiNd75El49aimP4yQ'),
  ('plants-as-medicine-753d6b', '12eCbV1wJMk_qL3DPKY3qaR_q_eu7CpojLr0tmJXHm5k'),
  ('school-and-garden-communities-d084f5', '1NpJLjpNVppJXHvGcC_W8c4Wwt5UhJA6KizI6QJtKZFg'),
  ('gardening-the-environment-82a8e4', '1vnOYmF90vIaodnDkjLtXQdSLoLdE38HALLK8OfcwntM'),
  ('leaf-collecting-172be1', '1CE324nZDL2kz_4P5TwDuvoX7Zx_NMwUz'),
  ('interconnection-native-american-traditio-b4bfaa', '1g1_hRDipt9_3YcSS2hka46gNwsuVo1sd'),
  ('plant-part-scavenger-ddf7ef', '1_ZSnx9J--WJCTJEp3YzqOly1axW_65nY'),
  ('sensory-scavenger-hunt-and-c794de', '1tU6lE36cuzrNIFb4jKLB2hLA4mAY9j7xWBH9jOHhuW0'),
  ('food-preservation-bcd7e8', 'lesson_bf1f76835a7446f78bfa843b7cbb99dd'),
  ('gingerbread-cookies-44a548', '181lWTGhtMXpO95d3JOAiPYXQe963z_Ru5Ibpvc9kbrE'),
  ('roots-113a6e', 'lesson_d4dda9480bc14c658352e00a2a49d02c'),
  ('varenyky-e36af4', 'lesson_4d119999d8d54a828d9cb217f6d98613'),
  ('plants-and-music-70a00d', 'lesson_47fca82c179549c2919a6eb283357b58'),
  ('empanadas-bde9b1', '16mykieJMT9T8b1iKHErAUFRhC-Sou_FckP-CzyJIOG4'),
  ('harvest-salsa-0c5aeb', '1iKSljm8MfixYb1HI9OgTKka-fBf9uln_'),
  ('aloo-gobi-dee3ab', '0BwC8Pf3ZwAXjNnhsOUZNLVRIUE0'),
  ('food-miles-87a477', '1tVWgHidAxvsPRMW2aJXd6YcFP9w0kbK6uOj_nbpu-KM'),
  ('kitchen-tool-identification-2f07d0', '18aRAD5iY1YxcaqTUZBhflNDAstEAHumK'),
  ('african-american-foodways-cornbread-and--6821f4', '1l7A2jTOeXN5rV-dOhb6eH59URYlCYK8BF8K-xsd_ut8'),
  ('what-does-a-gardener-do-1770f1', 'lesson_c78f6845475d4956bb9a038448bfea0c'),
  ('what-does-a-gardener-do-1770f1', 'lesson_e7dbdb5dc324470392f1b761eb62fac8'),
  ('foods-from-around-the-world-caribbean-is-6c992f', 'lesson_8be5b41f08bd43a99ac8cb113cc6dbd0'),
  ('growing-indoor-edible-sprouts-85449a', '1cwCnyYH_67kVHNbgkbcP0UmGn7vjRenOyndkaR1r1SU'),
  ('black-panther-party-and-the-free-breakfa-9eee2d', '1ov2wUSmaHCy8CwpBt_T6ADqB5jo6QC2IzhqlFBrzYNw'),
  ('three-sisters-puppet-show-16bd99', '1zYSlW4BcZajmrZMuhUiRt6zd7hpQWdDFr4SMCuEhG48'),
  ('all-about-pumpkins-830be1', '1vlKyiIiQPjoJ3Ek790STQlN9Ie87bYNbENpPa52S8Bg'),
  ('2nd-grade-decomposition-experiment-part--35ff28', '1J2HY5aTORYqL2MLI96g-357msUdFSq82SlqE2PHsUl4'),
  ('2nd-grade-decomposition-experiment-part--35ff28', '1UCyriRP14jUWMetMP6Olivo6XTS3COl14Et8dtpmkPs'),
  ('street-vendors-chicken-over-rice-f6e41b', '1T1sgLmsWzEYkAXNvsX4NMitYf0Au9o0Y8QZEsXpcPSo'),
  ('compost-relay-stew-2a51f5', '1730LjSjM6rScDdd0uqVm1JHFsiomc3yi'),
  ('our-garden-community-d5604a', '1JRUHeRL6Ttr5hGyvdU-a5uqsjZC7fBWx'),
  ('salsa-toast-27c8bb', '1sMS_PNeRlanHoPh6iQDCJ4wVcQ5HPsrP'),
  ('all-about-birds-d0c2f3', 'lesson_7f6a2a772f044c0c87f98f9cde200320'),
  ('sweet-and-sour-roots-ed3232', '1xdz4aJqRcHYaAluj-x3C0VoQRM3UNy-gERUvpuOuwcM'),
  ('kitchen-garden-intro-e3c509', '1cS3llhLF1k2bwgwz1f62fWk938evVGRE9crGuAWT3_g'),
  ('tortilla-espanola-e790b7', '1JEpJpbINYmbIN9j5W2dYrgIW6e0EqpalMa3kqm_53cI')
) AS v(group_id, lesson_id)
JOIN public.lessons l ON l.lesson_id = v.lesson_id
ON CONFLICT (lesson_id) DO NOTHING;

-- =====================================================
-- (4) Pre-update guard — refuse if ANY present target is already retired.
--     Reads LIVE lessons.retired_at (via the snapshot join), so it catches a
--     double-apply or drift regardless of what the snapshot captured. Aborting
--     here rolls back the whole migration transaction (snapshot included).
-- =====================================================
DO $$
DECLARE
  n_already int;
BEGIN
  SELECT count(*)
    INTO n_already
  FROM public.lessons l
  JOIN public.t4_dedup_retire_rollback r ON r.lesson_id = l.lesson_id
  WHERE l.retired_at IS NOT NULL;
  IF n_already <> 0 THEN
    RAISE EXCEPTION 't4c ABORT: % target row(s) already retired — refusing to overwrite retired_reason (double-apply or corpus drift)',
      n_already;
  END IF;
END $$;

-- =====================================================
-- (5) Soft-retire the losers. The retired_at IS NULL guard makes this a no-op
--     for any already-retired row (belt-and-suspenders with guard 4).
-- =====================================================
UPDATE public.lessons l
SET retired_at = now(),
    retired_reason = 'dedup:' || r.group_id
FROM public.t4_dedup_retire_rollback r
WHERE l.lesson_id = r.lesson_id
  AND l.retired_at IS NULL;

-- =====================================================
-- (6) Post-update asserts (hard failures):
--     - every present target is now retired with a dedup:% reason
--     - snapshot row count matches present-target count
--     - ZERO survivors carry a dedup:% reason (survivors must never be retired)
-- =====================================================
DO $$
DECLARE
  n_present         int;
  n_retired_dedup   int;
  n_snapshot        int;
  n_survivor_dedup  int;
BEGIN
  SELECT count(*) INTO n_present
  FROM public.lessons l
  JOIN public.t4_dedup_retire_rollback r ON r.lesson_id = l.lesson_id;

  SELECT count(*) INTO n_retired_dedup
  FROM public.lessons l
  JOIN public.t4_dedup_retire_rollback r ON r.lesson_id = l.lesson_id
  WHERE l.retired_at IS NOT NULL AND l.retired_reason LIKE 'dedup:%';

  SELECT count(*) INTO n_snapshot FROM public.t4_dedup_retire_rollback;

  IF n_retired_dedup <> n_present THEN
    RAISE EXCEPTION 't4c ABORT: % of % present targets retired with dedup:%% (expected all present targets retired)',
      n_retired_dedup, n_present;
  END IF;
  IF n_snapshot <> n_present THEN
    RAISE EXCEPTION 't4c ABORT: snapshot has % rows but % targets present in this db',
      n_snapshot, n_present;
  END IF;

  SELECT count(*) INTO n_survivor_dedup
  FROM public.lessons l
  WHERE l.lesson_id = ANY(ARRAY[
      '1NH0MZyhGNTdv3oPLf9pnmha8R8GOvPoz-_5MLxnS_xk',
      '13FPqZmdrIamQqrzLZUoeLt8CGTnP3vNJv_C_q5gyxjA',
      '1XLqd7Hrxr-lacieyRdaVsSBIdOOj-k4QW-Du8Dk3VXE',
      '1wp71sAPQQycFDAHX_k-Tk8fpzz-bb2FW',
      '1gr1mOTpvK0-t559hYZyGsQ4nnRlHC4Zk0uXQHgkqutg',
      'lesson_be063faef5704613af4fa8dda5864e88',
      '1pzcXwFx2S-P1q88F1QIhdLKHQiVvUwSq',
      '1YeuuUtmBUDf4OXVVfrSgSGOe_iaTEAz4',
      'lesson_8bce4ab6a0e6441b8ca1a49d620f5532',
      '17y_7ZaHUNVntuTL9Nkzm7rFHewK4UVcL_DPeSRcWk0c',
      '1Dz-Jv4cV0N0ntxZ8z0VcRgenI0hpZuOIDJuPbEvr7bI',
      '1gh1_OqCpnhDkGOmte5VIdIkEkU8_HpXs34KdcSuPkrQ',
      '1YuKoPyuJb5ImdgY1vTne8snk8VQeCCAjaPcJcxWIfhM',
      'lesson_fd594f6d103e41caaac34399cc1c23cc',
      '0BwC8Pf3ZwAXjN04xRGEwcl9Cd0k',
      '14j8QuDeVIPE6KlYqa5ebWISE3iiSVuq8',
      '15pgBlVdHdxpRCD22dmwzIgG-aBgHwe8dK2BNzg-85ks',
      '1A34UK78EbtdHIVeiVe0lNiLJaJ557y-JlS_o673-hmw',
      '1HHuEkR4gaoN7_Q7mlcteiDQ93glIfluzHF9sZSfZ0k8',
      '1Yy7iv3vxPHukKFooYce0yr5BOqUcqprM2rhUWX12Cgo',
      '1_YYC5Yr7thlhsTuEA3X3bnsVLw7jMttBAUpoxiud7sY',
      '1FUQYevNBKMdDFgZYFGyPDT90O_61dVOf',
      '1JZ2pkduAlf6OArWToNs4xxPEMkhLZKNnjX5kKN0nQuo',
      '1d1KP9lfI6jQdF9sBU74ncPv36OZZbTfm',
      'lesson_eb0b8ac045ab4dd8a87be6c8677454bb',
      '1VdSjKXnC33YNrhzBrCS_P4g2dP3nZrjnA53rBizPesw',
      '1kweucRDWEFk_Hi5LM_9M9DebTwKVZ6U0nhO8oM15sFk',
      '1ptt-0pUVa3KAR6QcuMQZpqFG3ISZGxMXudLgQmSbwxY',
      'lesson_b76499942d7443cd8db0dc33fbfe73d6',
      '1K0zdfgOhbMmfWLeSwPfpz3dJ0RM7fLrAilQ2Ebfjilk',
      '1OWqO3AwjSxS-em8YXeo1rB4pD8dHTF7bjTyMxYHkEx4',
      '1hcy6K0I14Kl4UOgNrNoWz7w37_3MV9lLkXAJ29Btk9Y',
      '1Bpg8H3y_CHtZ3gqSfoCjm0rldcaGxGOq',
      '1yCK6hD1_eLxD-kyj2EH0BUxt36yC8aqrIW8JY5M0ZpA',
      '1iqGFHrQ0rWfyoLo4R4n8FO9N-S7LW1ZpalaLNF5_Tmk',
      '1ooeavtd1AUn9ZlM9vDS9J9g3rBvRQJ48Hk4lhTzlDw4',
      '0BxEc0RZeYtCiUGNLaHJQSUFoQVE',
      '15uTWnv3aOIIeOLAhCjiA-9cG9xZlBKONpMZt-oyJYEQ',
      '1UOqNBD4kfdZth-hyfkGvYat_lVxgIscn',
      '1f1FVc2FsYYwFtCFWDRAxSfsT3BcPC1E5',
      '0B25CqYCC7Ofbc1Z3X1Y1cVZFenM',
      '0B25CqYCC7OfbdE5tczBRUFoyS2c',
      '103KB5-ciAEHWVDI1r02KjR3No2WSzazE',
      '1PO5ty9ZydWYF70IhHKtyk4zq5oP2FeSW',
      '1lGcRDLkd7n5-CulckQb-rt1M5Q7SeA3K',
      'lesson_426e363f5de14520b790695e25b95cda',
      'lesson_be2157750d064fd3b7428af9c1944b59',
      '1qjmWKwdXaFMED7hu4RuSgSEOJvxwEVGGWuBoLHjU_pE',
      'lesson_03de6aa8ce094d0b9fd6518830e3eae7',
      '1dqVb1CXvx_YVQ3cH8UuoGxYZ5A2MzU-bi8n4fZqBTXQ',
      'lesson_d352a03cea784f46bbda2a545c9de44a',
      'lesson_7888524cfdfc48f2bb5379e4edb28742',
      'lesson_adb1d7099a92424eb7172e582329f6a7',
      'lesson_e472ad47218645fd91cc28570e082472',
      'lesson_8067735e96df493b85b61f4b5bc11308',
      'lesson_624b28fc83214ed1b3999ccf1ea5d085',
      'lesson_21119471ac47403e89286545e8036d94',
      'lesson_36ef1fadbcb8428c976fa5f575c3390b',
      'lesson_df09326b3497429cad55727f6d59d477',
      '1QLiWw08Qi5CSB6uMwwm27WDgMNG-LMhtqOu6z85VRkk',
      'lesson_f0cfb993e2b94d4c89f272eb4269cb26',
      '1dTMg_5AdKV5cJNnt7_L2cXhTK9fmJr8U',
      '1kk7iWzUOFQY786Ilr2MqaEiCmfv1EpUm',
      '1LiwBsr5PqwM2P3xLI90XXuhD_Edaho5LtK7WclwBmNw',
      '1ncI1zLlOFK4Rn0sToxLR_a5KzE8DfNSfeCLdT3gRXQI',
      '14fk_yAGgoUM0I7iJDOKaSdZrww1HHPPj',
      '1JNKJikW1P1lCE4zlt0_2S4F2mNIRF7qm',
      '1QDqLmtbhClI6Hrx-QNUclaTYfsv5Z4Mh',
      '1sHwSvaFaZC9wpHOqr-dQBMEl-paf6zZV',
      '1CKiTtmLKaCFrswKuCxw8btPkztv_Gu-c4cJI5kwtMKw',
      '1XztHqBQ5DbhqPyG69LNzv6OtiPMJCptBzaMDXTPMKsM',
      '1CAKF0L0SYp5fgaXqZrrb4G-K3LzOu56phWV9JFg67U8',
      '1OTWsMqlZ6xubbc53zT7V8wq7B-lhOW1BvmI0i_odT4c',
      '1lfH8xM8MZtOtYf7EIXqw7I29Gpd90_s2GBMW9KWmE28',
      '17upoxUN1PvxQ8VqOOVD-_lx16etNxNM09o5X-hKQzI8',
      '1Kcxu-MFMtb7JZwxracAS-XPjoTKIc6tLyUfsrtHTbD4',
      '1M7m_WxtgZ8EJtZ0Pkii6RV5G4iNFiJHOCTXXvv6Viis',
      '1c7yZMrlhHmTwTdmiFGLAVAzpESFDK9pIyJeJwHrn-PA',
      '16ZNi4Oeu5j4mMOZrEk7OYlrqIhSsqj_f',
      '1hUNwNfHVudR9tl-UZ8wPn9dKB9h7t33l',
      '1FAkVWiqdQ-B-6OSIu2C7BlD-cYmOG2OD',
      '1NnjoeztiUEqcOwfduLqA4NYUrpS405q-',
      '1YOJ1pRdApcO0q0dfbP-JjM6NhLFiDKEf',
      '1d0ialxuX90WarbOqoWK5jcVS27hGj7eR',
      '1i84KNGaRDLMPQpQc8LN6ZqDop0BLyPSQ',
      '1qlwQLN_WX_BUzSZuxFhAvxjb_b95pW6V',
      '1s10FiZW7qM_IhOUDiY2Wk9yJ4Zewcpy-',
      '1HuffJuy_-bVzIAm4GxzBhG3gOtiRoAKBBapswfhZrCg',
      '1NqjpqXV8soDQs2W9HonavtlxQT4MbFI0H7pUdnH-mEI',
      '1yfwfesww-3BopJBAbtt_C0JUGmyJiUDW2ZrW4Pq05Ow',
      'lesson_b730f385a226452e98a7c3f972843e67',
      '10RLQJ1UxwvhRyz7trKL6327fIt3Cxfr5HT1z_p1s-ds',
      '117dIoZ0oEp4TQdzDWnS3EXkvP0rLjvDr_U__A65VoQk',
      '1Ck6V2TB3qvgmK3h6vVGp_FMGtKQDz6FVoBWjjj-Vm2M',
      '1NF_sOLKR8um-3T9Eck-_i6j-GEwv0X58TqqJk2Qu350',
      '1YyZtfvujMDeYYtAEYDHfh-Z-BO1SxpeV_6FZinilSts',
      '1iUmZQtejAbOYDkxNhEj47s_O0a5qvo7OskHw2-KhCP4',
      '1B3Phuk-DzUJFDHJKfg9RPlolcBWMeaq6gwWRjOfhU9I',
      '1uDDPxAKSjEPYMU36W80bEbSMa_YuuGPNw62CXFGD6hM',
      '1mAI2VtQntfWhUtIEKT1xP6Q028Hx-Jyqx_Xr-V2vWkI',
      'lesson_f5a5f81079a94652b92e4f94f5281ca1',
      '1Cj-iXBv_-EE4blTLhBngUNjYtsSUUTFWcXTRRTXOLD8',
      '1TNen8KVizYd-al0B8XTA9wY-3s5O6Rm8aJQDWPhpz7k',
      '13GXO2eOzTXCHLPK4mEwsMRuaIWr6RxWv',
      '1UVFHNwDVKhoZU5cmxCASVc4M7kMP_EI8',
      '1XmATwlVih6GFIL4MOlhDC2GXQuex6V0W',
      '1shFHdzN2mlZzqo5tyIIH3-NCPZRYxO3B',
      '12afDXwtfouvdhbJWIlpB07gF2L-N0KDg9Ws_OXqcca0',
      '1gLuwRIEfiYyfqztlMGAEOeAuJI1flmj7',
      '1iTH3kooXMEVDsZaV1wqVGLvgXO3c55lrxtsIHGlaz28',
      '1mSiEfFWtu_D2cg1A0X4K8hcas-p040hoXB16p-hPAkM',
      '0BxbI_EfhfAWTWUdnV1RTTF9WaE0',
      '13uPiVU50hQcj_Ho1vEhfJmVeK8BFTqb-0BdHmx-wIdg',
      '1AVz6xA4ZJO7mT3oWSJ2unIiY0APuj9yg',
      '1BQdTnCzvCWc7u6MA9ey1HFm-H1g-fXdcgGXFU_Fxzww',
      '1XlUFSs_ls80ONwWgGCPHHA8re4kfmzgL',
      '1fNjAzV9JZhGsVCvQZui8jtoSfcSBEiNkU9yhTg55lEQ',
      '1w_JBTJYmqF0qcXiOtV_nV32nphCjD8uEYRSHdHyROFE',
      '1zrWJ0unlwyo7hjeb9ZG2betTOIaitwzN',
      '11WKWZvHkycA5yOZQcRaCViwyoMSGUS9sve64q77T5E0',
      'lesson_3aaa27c0096a48368cde2804832ad07c',
      '1J4mAP4OTmdckb2AiebgtsosK9xF60cr8W6Cz9lf8AOI',
      '1fqFWrvA5MWkoXTYM2_RbexrcVC4xNuJBqwlIfVCPDUA',
      '1MTqszq20L6jM1i-f19D2PzfrfTunNRmkP-GAl-ZYO9A',
      '1ZAAaZJTBtqnmTbuf-5LujtpCm9ebqSl9aIGw48PZaCg',
      '1-AYK5D4_VEmu2ZWgFtaJItK_rn3hhoEK8YdPr_F0Ows',
      '167u70cUC4N1EJ9H-9IAl1c4J7zGZ6Ta_LOvDStgqGks',
      '1ChYFdztQt1U-EK4aOzZ6XkY9fKqTCawKlmTlTajQRvg',
      '1d2ELOzXFQ2h8bIgluCdDXvpmpYXIi2IlFtmZbkmy_HI',
      '1m2sMUa9Qjkzqz9dU6CqAkAReX6-92gUC8Va8Zl_EdMw',
      '1nNPA0q0yh9gE_Qz7Nx5_jmUIqhkOAOWrISWtv7pYLs4',
      '1p-OKyRxUgFVkGZaq4DFA7wIvRd5-FVWZmnQngPaE0p8',
      '1u84NuJq0TStf_mZlUtht2OjNnf8bKkSbBuwEBkDSCfI',
      '1v1gv3D6WAbUZCBtnmOjxJsvKZypAhKhfhjSx9ZVuuXU',
      '1VDKC8Qz73JtOdPdK1u3bpEleKNx2cPPlCsiec6B8nqg',
      'lesson_a6f5b5177f0642828362f61093e54de5',
      'lesson_ef043bcf99f44965a0cc5dd6aef52a82',
      'lesson_769f32694684408fbacbe1b02fc9d8a0',
      'lesson_011467fd86fa4339a745803f8643fe84',
      'lesson_a689a2c8fc7b4f2daabc6ecbaf4fdce3',
      'lesson_d73c3abe21f04406b664d7a9d899859c',
      'lesson_e8fa030e63bf4a9cb13b95448a3450c0',
      '1RY1H0XMEOYQtCk0mV7xaKYBPzoDqBm2m',
      '1epVkBIQPhxeIHEbzSQfogJ0sEVptkm7qmhyzQvfN_38',
      'lesson_7d34e6ab88b64d8a855507ac6c47db20',
      '0BwC8Pf3ZwAXjS3JwZUFpbVlETzA',
      'lesson_36981b6fe32741629a2ddca67acb3ac2',
      '0B9X3sp9nlAgmVmZpaFd6clptWTA',
      '14MTTw-8EGeW0BMghM8C8imcWlKXB7P1q-SH-84m7E8U',
      '156gQEcjZxXoqU9te_0TUzxg0grMxFPD1',
      '1vFSTeTtZWM-xc7mUfvEclO1YCmIMiqR8',
      '1XauzA4pCa3WHn-zH98891apaw3FhAXAl',
      '1N7gRmGohK_fCtpiHemQTl1-Bpg-hwOF9',
      '1HkHvHBFdGRIu0dJ1GmBiq4OzEXrmRW60odAvls55gZ0',
      '1QfQnwMEhSLMwZ64WgW6MVG6aAX1o5ii_XkxLobFUrns',
      '1olvVADiZt-jO3KhD72MhfPNSmiqPG95iPlrgRbsS63I',
      '1ytK3-gaDKtmSpYvuHnrci4DmazDybXrL6SW6dmoUf78',
      '14wTm_zkFDwSqkUBJj01zdY2Lq1D6-eXdj6BQcZwOrQ4',
      '1E2vC2aWzAzrAW6-T68FPK7QM-ehDmISnduOQcsAkCKA',
      '1NHQd8BVmNECNgkMV4FeJjC5fzMxi-Pcp',
      '1GRwdy72vU9H6xe7txN6D3zwUnSzLyC0Z',
      'lesson_3f33219774294a47bc7ba0afd5f29311',
      '1LYziMRy2LTXb4W1nTpjrDCk6J73XILqo',
      '1uwZRLYoxThlJxDq-vV3cePHmEMGMCpj5Opk0nHVvqqI',
      '1xwTiqazvuLxwYiNB-y6xLaRRVFkDkvOgYroXPstQLjE',
      '0B-9rQRyZMNzUZlFLYlc1Um1oZnM',
      '0BxEc0RZeYtCiVVRTV0xRM2FpQ3M',
      '1cX_lHizAQAD-XccT95OugIwfmcCXIWsI35hk4ewmF1c',
      '1e0UWQYtEYVnGioomuIHx4LwJn3sJ8wKV',
      '14H58lppqxAt24rwpI0B3fbPqZ3y0YIXxPc517Cz8TP8',
      '1TF7HI4p0Ibx1qTjszaqbKcpvtz1VlDbBjhjTT2YB9cM',
      '1J1ghuNNBGsbbVydOoWvfJwIMCignE2qc',
      '1Yx7Yp7W90p_XqfF-n3M78MblwCsQykbjVAFAofwT6GM',
      '1UnaUuap0s73WmekEM-m0amMyaww8T_bYS6JeNFgZmmY',
      '1pGzazTHZbfbNIafJvpMV06eAyvsNTPc6wG71K3CVQr0',
      '1EPkNrvYIN_1pGe7zRjikBwIo2FcfNVxa3QADs26qYf8',
      '1kgvrmzkZ7o81URjqGwoq1DK0VicdTIHfvtXEvvmfxK8',
      '11ItiMGkBnyCYE13EhzVmUCMSeYivseKkcDcfe-26UEw',
      '1fEkd9o2C1buVhZsjd8xzOoy7Sfl2FsIW',
      '1wjRd4v-bAua4Tk_8KD9MBl1FwPU4EfXf184NRueNkTA',
      '1Bbnmk4k59LrPdymvyAk-SNPM0NvJEBA-Eil2kSits6E',
      'lesson_366d2fba34d34509811093f5adfb744b',
      '1ESUFQVvS6fSejIOM76AL0PIyY3xJKtyW',
      '1Ju0BjlCu9t9W_SuQCJnVruaVZxj8r0FhjcMmbwJTPI0',
      '1dHNasB4vEvH8G_OIy5Y7kVTOjXSovx_qLUGVB2UYk-M',
      '1v7aPRuAM9q1jdffDr1IqgxZUKqTZ7By-',
      '1LIpgLeP6F2iRRUklhiZKEKNIJm4XNfwNuO67ilEgwEM',
      '1uORjUwtJm3Ske0tI3UmZ7RG-IkfsN7v_',
      '190fsy48bYmHRsn49YEZh1Lkn87CqpqaZQoKzAUJMUYc',
      '1OJtcaCozwbHj2H2CdzPvYQOLsP_ISIFYMYMzRiIB7LU',
      '1aR8TJy6wbqotVca6i3aazfACXM_7UvrxUYHEFAjJWiE',
      '1eEd1a3R8E3vqbcXUQJ-Diht81xOJDdRJIBQbF5CiBa4',
      '1QS2lWpFV8l7hee8qKZ_OP4HWGQng8BvM',
      '1eE4tbHy8L1mQhWWcpgMRetRDWzx5P1YS',
      '0BzCUl-9h7sgESGZ0MThTY0NBYVE',
      '1X7HadA1WaR-hNBFIHvAUsFKborDGE5eT3Lhg5Dp9CEI',
      '1_WlZmDJv8Ql-sCLlOyxr2qL4zeb1GQda',
      '18c3H1c92Dv95kfdZlEe5D0HdbNGdWO4B',
      '1PJDsQ0vRviNdY64ny3ZoytCGDuWRjP__Yo9lMFhMh_o',
      '1QNvw2_DVlrd8079Jwgyfb8jQzjho1Ut5',
      '1quejMyRwvd1YerJBW09hzoaiFmkmrDPN',
      '12ZjWQaqW6hOPDo16zi9PN3iG92jI4KLz',
      '1482AqITl5WxMGPW5wNNh8wOBShm3kbyU2cpqfYkuxuo',
      '1Dkx1Q--fGzGDCAu3kx5OTsuRa_lRY2agdiMqyfn2VpI',
      '1t6oKO1wyQjRdVqTRsp-aKNfQ-vEL87LwZWNfNqwej6Y',
      '1xaMyZf2OTGpX2GAD8-qgYADXHw1vTevByfs1bJ55lNs',
      '0BwC8Pf3ZwAXjcm9MR3JaaHgxOVk',
      '1I4d-aRwxi4e3z07fv7wIz-InK8XagdQa8uMfqa1NTtg',
      '1ZynAlPlWZsqiotLYrT7PTASgINLs30N7ETVQYp-AWYQ',
      '135RmnOeDA2UjHnKmfQIh4JylpENfk4CN',
      '1LO4p1z6TBKdq_ViV9yPH42ZD7_sJhSEU',
      '1ZvGJGmE8clzkVCOe3xFkdWUpckJ2NF5IbeTmkQXWKZw',
      '14VRzSpor9seknAFnsnI_HCvpMVqf6suG',
      '1cPBs_lw1xaTCRZOqr_8WKTxwChu6vSWhGk8U7aMj_OI',
      '1K1tlc3--Dv061Qi1A1AKOGW6_L19VXSTRtKHfe73bjY',
      '1n8wS0X-dXAw9sfQuLFgsMg_kNvACph3cT4yd9p2i1eg',
      '1wFKZlUxu_aavugzZuK31_MHzonxS3wC1B1wRQ4c4Nbc',
      'lesson_730a61c3737c498fb82cb1c074d1d5b1',
      '1IHvZCWETI83NFCVhWAB57sE_cSvc4txycBQtaDzS8cA',
      '1uJV8xVyH95GQO1gVcnllbhv7kUgnfK6P9BrC0Ao4aBg',
      '1C4REdzYpDhJIgiyXwTiTnPppPNv5c92b_l3a21MDCxI',
      '1k7KqowpILVoRe-X0sOiOtcwJyC8_fJ17nwLu-DW5_r4',
      '1bEoQ5a8y8wHIsNQsEGJh-F1scPUtF1mkFj9o5jooAJM',
      '1qwbgUIiZgmzrK-hQIJZaieaZTnq1sLev-YKHDnncQXM',
      '11zvB7FSc-Z41_BSf3zh_Kc17TZhZK3lb',
      '19hyKX60yBWKlC9CcvA93l9Q5q6CfyRXi2xWNFvkz5G0',
      '1bmjJf9tTDt5y28DB0xszcouBQKr0Ud8ZdkNtelNCURE',
      '1ejnMz5mRDOi4NIPakPgEpKCKpnPz7yx-SAg07-FlTr4',
      '18sSQUw48YOS12Egcpbk-N4MR3HjN-CnaoI64nzoEElM',
      '1nbnwFytunU5eIfH7IpqfM1wXrqEeU6marG3o6lOBJdM',
      '173asHBA5_t4TpYSZjUJWaophzm6NCEzrt3GlIt0ssDc',
      '1mTrOat6NRL6z3SqwXqINpikZYdyL3VyqUr74t1kYYQA',
      '1PAsbX7TiCV0vlvFwtD_tteWiWWdCAcCmttQEv2oOBwk',
      '1xQebmPuWM1ZFPnfDCekLW5qSatOXSoDtJKWRvJQPGnU',
      '1NKjrltsfTTjAT5IZKGHiiovZvRcvhfJx6rPVn-lbYFM',
      '1YnlgMvzSZPf62gHtWozhokKR47TOZUkf',
      '1d5L9ARkIeBj7VyrV-4x9xtC-V4QbRb3U',
      '1vY0gOo9IooV6W9uAVYskU1G0byTHEfzIPHnFMGPKQQo',
      '1bjiET8ffFpU5_gCMgJBiTDPuHhE0lCPGBnv72LXzrW4',
      '1u2kn0lEbeRsF7P340khtFl7TV1G9Xe1teh7QEkWIv58',
      '1JcQB3OaA0ws5SoJwanWrSOxAZHGuc7Xt',
      '1dYfqKvRGyB45l5D-3KEN9Fx6-lFsNckvakBtMQq614k',
      '19ZBXDDQ5vZ2y5LrJ8w_7D7sqXSQNQeUF06ovPagaQo0',
      '1FNaneHQZ6xx_jBlM6429vbQ8w_bMBYzOlF9R-Wqq_g4',
      '1V2Xt4cB9K19aItujCO8lrshz1YDSW022Okln4jI0ij8',
      '18LGHGw5bid1uFmapJbJlSUlwX4-h7oUGNoZ-nu47egM',
      '1kSgjpijAnIVj2ocA_UHc3ggMT2cdk8Z7',
      '0B5ixnZghJTD6QWZIRUo1cWZ1NWs',
      '167xICOA1ZnU5mHoUIvU6fYb2zv8Km6lU',
      '1w0c7tESqksEPlQL-Fj1tpTL3i2ofmN_Agq-UwwqErBE'
    ]::text[])
    AND l.retired_reason LIKE 'dedup:%';
  IF n_survivor_dedup <> 0 THEN
    RAISE EXCEPTION 't4c ABORT: % survivor row(s) carry a dedup:%% retired_reason — survivors must never be retired',
      n_survivor_dedup;
  END IF;

  RAISE NOTICE 't4c dedup retire OK: % present target(s) retired (snapshot=%), 0 survivors touched',
    n_retired_dedup, n_snapshot;
END $$;

-- =====================================================
-- ROLLBACK — see sibling 20260702160000_t4_dedup_retire.sql.rollback
-- =====================================================
-- UPDATE public.lessons l
-- SET retired_at = r.prior_retired_at, retired_reason = r.prior_retired_reason
-- FROM public.t4_dedup_retire_rollback r
-- WHERE l.lesson_id = r.lesson_id;
