-- =====================================================
-- Migration: 20260703030000_normalize_kebab_theme_values.sql
-- =====================================================
-- FP-02 — normalize machine-style kebab theme values (e.g. 'seed-to-table')
-- to the canonical Title-Case vocabulary (e.g. 'Seed to Table') in BOTH
-- lessons.thematic_categories (text[], the authoritative filter/search store)
-- AND the legacy metadata->'thematicCategories' JSONB mirror, then install a
-- table-wide CHECK so the drift is structurally impossible to reintroduce.
--
-- WHY (FP1 audit NEW-A, docs/plans/fp1-audit/shelf-frontend-ux.md; tracker
-- docs/plans/2026-07-03-frontend-polish-tracker.md FP-02): the search_lessons
-- RPC filters themes by exact case-sensitive array overlap against the
-- Title-Case values the UI sends, so kebab-valued lessons (~74 active on PROD,
-- ~10% of the library; 86 total rows on TEST = 66 active + 20 retired) are
-- INVISIBLE to the Thematic Categories filter, split the facet buckets, and
-- leak raw kebab strings onto the public lesson drawer.
--
-- This file is GENERATED by scripts/fp02-theme-normalize/generate-migration.ts
-- from the canonical vocabulary in src/utils/filterDefinitions.ts; DO NOT
-- hand-edit — re-run the generator to regenerate. No lesson_id appears
-- anywhere in this file (the target set is a value predicate; the snapshot
-- table captures the actual ids at apply time), and the 7 value pairs are
-- generator-derived, never hand-typed.
--
-- MECHANISM: 100%-mechanical mapping — every kebab variant measured on TEST
-- and in the PROD audit probe is exactly lower(replace(canonical, ' ', '-'))
-- of one canonical label. Guard (2) re-asserts that relation INSIDE the
-- migration, and guard (3a) ABORTS on any theme value outside canonical ∪
-- kebab, so a surprise variant on PROD fails loudly instead of being guessed
-- at. The element-wise UPDATE preserves array order and cannot create
-- duplicate entries (guard (3b): zero rows carry a kebab value AND its
-- canonical twin).
--
-- TRIGGER INTERACTIONS (verified on TEST 2026-07-03):
--   * lessons_normalize_write (BEFORE UPDATE): section (F) no-ops because we
--     set column and JSONB mirror together; its hard-failing
--     _validate_meta_enum_values checks metadata activityType/tags/CRF keys —
--     probed zero off-enum values on all target rows (re-probe on PROD before
--     the morning apply; a violation aborts the whole transaction cleanly).
--   * update_lesson_search_vector_trigger recomputes search_vector for the
--     updated rows (theme lexemes go from compound-kebab to spaced tokens) —
--     expected and desired.
--
-- ATOMICITY (t4c pattern, 20260702160000_t4_dedup_retire.sql): this repo's
-- supabase CLI applies migration statements in AUTOCOMMIT (extended protocol),
-- so without an explicit BEGIN/COMMIT the section-(5) UPDATE would commit
-- before the section-(6) post-asserts run, and a failing assert could NOT roll
-- the write back (c02_retag_apply:59-64 documents this first-hand). The whole
-- body therefore runs in ONE explicit transaction, with a SHARE ROW EXCLUSIVE
-- lock on lessons serializing the apply against concurrent reviewer edits.
--
-- CHECK CONSTRAINT: unlike c02's NOT-VALID-only precedent (18 grandfathered
-- rows), post-assert (6e) proves ZERO off-vocab rows table-wide (incl.
-- retired), so valid_thematic_categories is VALIDATEd in the same transaction and
-- leaves no residue. Operational caveat (carried from c02): any future write
-- touching a lesson row must keep themes canonical — vacuous while the vocab
-- is closed, but a vocab change needs a new migration + regenerated CHECK.
-- NOTE: supabase/seed.sql theme values were canonicalized in the same PR —
-- seed runs AFTER migrations, so off-vocab seed rows would violate the CHECK.
--
-- Rollback: sibling 20260703030000_normalize_kebab_theme_values.sql.rollback drops the CHECK FIRST
-- (ordering is load-bearing — restoring kebab values with the CHECK in place
-- would be rejected), then restores both stores from the snapshot. The
-- snapshot table public.fp02_theme_normalize_rollback is LEFT IN PLACE as the
-- recovery artifact (a post-launch cleanup migration drops it together with
-- t4_dedup_retire_rollback once PROD-stable).
--
-- Pre-registered environment state (measured, spec fp02 §2):
--   TEST  (2026-07-03): 86 rows carry ≥1 kebab value (66 active / 20 retired);
--         exactly 14 distinct active theme values = 7 canonical + 7 kebab twins;
--         zero strays, zero rows with both twins, JSONB mirror == column on all 86.
--   PROD  (audit probe 2026-07-03): same 7 kebab variants, ~74 active rows
--         (29/24/16/12/5/4/4); retired-row count unknown — the set-based
--         predicate handles whatever is present and the guards abort on surprises.
--   LOCAL (seed): zero kebab rows → snapshot 0 rows, UPDATE 0, asserts pass
--         vacuously, CHECK installed + validated.

-- The whole apply runs in ONE explicit transaction (see ATOMICITY above).
BEGIN;

-- Serialize against concurrent writes to public.lessons for the (sub-second)
-- apply, so the pre-guards (3), snapshot (4), UPDATE (5) and post-asserts (6)
-- all see ONE consistent snapshot. SHARE ROW EXCLUSIVE blocks concurrent
-- INSERT/UPDATE/DELETE but still allows SELECT; released at COMMIT. (Requires
-- the surrounding transaction — a bare LOCK errors in autocommit.)
LOCK TABLE public.lessons IN SHARE ROW EXCLUSIVE MODE;

-- =====================================================
-- (1) Rollback snapshot table (service-role only: RLS on, NO policies —
--     mirrors the t4_dedup_retire_rollback / c02_retag_rollback precedent).
--     prior_metadata_themes is the row's metadata->'thematicCategories' value
--     (NULL when the key was absent).
-- =====================================================
CREATE TABLE IF NOT EXISTS public.fp02_theme_normalize_rollback (
  lesson_id                  text PRIMARY KEY,
  prior_thematic_categories  text[] NOT NULL,
  prior_metadata_themes      jsonb,
  snapshotted_at             timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.fp02_theme_normalize_rollback ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- (2) Mapping table (TEMP, dropped at COMMIT) + compile-time guard: exactly
--     7 rows, kebab/canon distinct (PK + UNIQUE), and every pair satisfies
--     the mechanical relation kebab = lower(replace(canon, ' ', '-')).
--     (A property of THIS file, independent of DB contents.)
-- =====================================================
CREATE TEMP TABLE fp02_map (
  kebab text PRIMARY KEY,
  canon text UNIQUE NOT NULL
) ON COMMIT DROP;

-- GENERATED from src/utils/filterDefinitions.ts — never hand-typed.
INSERT INTO fp02_map (kebab, canon) VALUES
  ('garden-basics', 'Garden Basics'),
  ('plant-growth', 'Plant Growth'),
  ('garden-communities', 'Garden Communities'),
  ('ecosystems', 'Ecosystems'),
  ('seed-to-table', 'Seed to Table'),
  ('food-systems', 'Food Systems'),
  ('food-justice', 'Food Justice');

DO $$
DECLARE
  n_rows int;
  n_bad  int;
BEGIN
  SELECT count(*) INTO n_rows FROM fp02_map;
  SELECT count(*) INTO n_bad
  FROM fp02_map
  WHERE kebab <> lower(replace(canon, ' ', '-'));
  IF n_rows <> 7 OR n_bad <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: mapping integrity — % rows (expected 7), % non-mechanical pair(s)',
      n_rows, n_bad;
  END IF;
END $$;

-- =====================================================
-- (3) Environment pre-guards (whole table, INCLUDING retired rows). Any
--     failure aborts the whole transaction — nothing is written.
-- =====================================================
DO $$
DECLARE
  kebab_arr    text[];
  n_stray      int;
  n_both       int;
  n_jsonb_only int;
BEGIN
  SELECT array_agg(kebab) INTO kebab_arr FROM fp02_map;

  -- (3a) ZERO theme values outside canonical ∪ kebab. A surprise variant
  --      means the mechanical mapping is incomplete → fail loudly instead of
  --      silently skipping it (it would violate the CHECK at (7) anyway).
  SELECT count(DISTINCT v.val) INTO n_stray
  FROM public.lessons l
  CROSS JOIN LATERAL unnest(l.thematic_categories) AS v(val)
  WHERE v.val NOT IN (SELECT canon FROM fp02_map)
    AND v.val NOT IN (SELECT kebab FROM fp02_map);
  IF n_stray <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % distinct theme value(s) outside canonical+kebab vocabulary — mapping incomplete, refusing to guess',
      n_stray;
  END IF;

  -- (3b) ZERO rows carrying a kebab value AND its canonical twin (replacement
  --      would need dedupe; measured 0 on TEST and 0 in the PROD audit probe).
  SELECT count(*) INTO n_both
  FROM public.lessons l
  WHERE EXISTS (
    SELECT 1 FROM fp02_map m
    WHERE l.thematic_categories @> ARRAY[m.kebab]
      AND l.thematic_categories @> ARRAY[m.canon]
  );
  IF n_both <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % row(s) carry a kebab value AND its canonical twin — element-wise replacement would duplicate entries',
      n_both;
  END IF;

  -- (3c) Every row with kebab in the JSONB mirror also has kebab in the
  --      column (the UPDATE below keys off the column; a JSONB-only kebab row
  --      would be missed and post-assert (6b) would abort AFTER the work —
  --      catch it up front with a clearer message). Measured 0 on TEST
  --      (mirror == column on all 86 target rows).
  SELECT count(*) INTO n_jsonb_only
  FROM public.lessons l
  WHERE jsonb_typeof(l.metadata->'thematicCategories') = 'array'
    AND EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(l.metadata->'thematicCategories') AS e(val)
      JOIN fp02_map m ON m.kebab = e.val
    )
    AND NOT (l.thematic_categories && kebab_arr);
  IF n_jsonb_only <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % row(s) have kebab themes in metadata JSONB but not in the column — column-keyed UPDATE would miss them',
      n_jsonb_only;
  END IF;
END $$;

-- =====================================================
-- (4) Snapshot every row that will change (set-based — NO id list anywhere;
--     the predicate IS the target set). ON CONFLICT DO NOTHING makes a
--     re-apply after the rollback idempotent w.r.t. the snapshot.
-- =====================================================
INSERT INTO public.fp02_theme_normalize_rollback
  (lesson_id, prior_thematic_categories, prior_metadata_themes)
SELECT l.lesson_id, l.thematic_categories, l.metadata->'thematicCategories'
FROM public.lessons l
WHERE l.thematic_categories && (SELECT array_agg(kebab) FROM fp02_map)
ON CONFLICT (lesson_id) DO NOTHING;

-- =====================================================
-- (5) Element-wise, order-preserving normalize of BOTH stores, with the
--     updated-row count asserted against the snapshot in the same block.
-- =====================================================
DO $$
DECLARE
  n_updated  int;
  n_snapshot int;
BEGIN
  UPDATE public.lessons l
  SET thematic_categories = sub.new_arr,
      metadata = jsonb_set(COALESCE(l.metadata, '{}'::jsonb),
                           '{thematicCategories}', to_jsonb(sub.new_arr))
  FROM (
    SELECT l2.lesson_id,
           array_agg(COALESCE(m.canon, v.val) ORDER BY v.ord) AS new_arr
    FROM public.lessons l2
    CROSS JOIN LATERAL unnest(l2.thematic_categories) WITH ORDINALITY AS v(val, ord)
    LEFT JOIN fp02_map m ON m.kebab = v.val
    WHERE l2.thematic_categories && (SELECT array_agg(kebab) FROM fp02_map)
    GROUP BY l2.lesson_id
  ) sub
  WHERE l.lesson_id = sub.lesson_id;

  GET DIAGNOSTICS n_updated = ROW_COUNT;
  SELECT count(*) INTO n_snapshot FROM public.fp02_theme_normalize_rollback;
  IF n_updated <> n_snapshot THEN
    RAISE EXCEPTION 'fp02 ABORT: updated % row(s) but snapshot holds % — predicate drift (or a partial double-apply); rolling back',
      n_updated, n_snapshot;
  END IF;
END $$;

-- =====================================================
-- (6) Post-asserts (hard failures — any raise rolls back EVERYTHING above,
--     snapshot INSERT and UPDATE included).
-- =====================================================
DO $$
DECLARE
  kebab_arr  text[];
  n_col      int;
  n_meta     int;
  n_len      int;
  n_offvocab int;
BEGIN
  SELECT array_agg(kebab) INTO kebab_arr FROM fp02_map;

  -- (6a) zero kebab values remain in ANY row's column.
  SELECT count(*) INTO n_col
  FROM public.lessons
  WHERE thematic_categories && kebab_arr;
  IF n_col <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % row(s) still carry kebab theme values in thematic_categories', n_col;
  END IF;

  -- (6b) zero kebab values remain in ANY row's metadata->'thematicCategories'.
  SELECT count(*) INTO n_meta
  FROM public.lessons l
  WHERE jsonb_typeof(l.metadata->'thematicCategories') = 'array'
    AND EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(l.metadata->'thematicCategories') AS e(val)
      JOIN fp02_map m ON m.kebab = e.val
    );
  IF n_meta <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % row(s) still carry kebab theme values in the metadata JSONB mirror', n_meta;
  END IF;

  -- (6d) for every snapshot row: new array length == prior array length
  --      (element-wise replacement — no loss, no duplication).
  SELECT count(*) INTO n_len
  FROM public.fp02_theme_normalize_rollback r
  JOIN public.lessons l ON l.lesson_id = r.lesson_id
  WHERE COALESCE(array_length(l.thematic_categories, 1), 0)
     <> COALESCE(array_length(r.prior_thematic_categories, 1), 0);
  IF n_len <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % snapshot row(s) changed array length — replacement must be element-wise', n_len;
  END IF;

  -- (6e) zero theme values outside the 7 canonical remain, whole table
  --      (the pre-VALIDATE census that makes (7)'s VALIDATE safe).
  SELECT count(*) INTO n_offvocab
  FROM public.lessons l
  CROSS JOIN LATERAL unnest(l.thematic_categories) AS v(val)
  WHERE v.val NOT IN (SELECT canon FROM fp02_map);
  IF n_offvocab <> 0 THEN
    RAISE EXCEPTION 'fp02 ABORT: % theme value occurrence(s) outside the canonical vocabulary remain — VALIDATE would fail', n_offvocab;
  END IF;

  RAISE NOTICE 'fp02 normalize OK: % row(s) normalized (snapshot=%), 0 kebab remaining in column+mirror, table 100%% canonical',
    (SELECT count(*) FROM public.fp02_theme_normalize_rollback),
    (SELECT count(*) FROM public.fp02_theme_normalize_rollback);
END $$;

-- =====================================================
-- (7) Belt: table-wide CHECK, idempotent ADD (pg_constraint existence guard,
--     c02 P4b precedent), then VALIDATE — safe here, unlike c02, because (6e)
--     proved zero violators table-wide, we already hold the table lock, and
--     the ~763-row scan is instant. Empty '{}' satisfies <@; NULL is allowed
--     explicitly.
-- =====================================================
DO $$
BEGIN
  -- SOURCE: src/utils/filterDefinitions.ts FILTER_CONFIGS.thematicCategories
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'valid_thematic_categories'
      AND conrelid = 'public.lessons'::regclass
  ) THEN
    ALTER TABLE public.lessons
      ADD CONSTRAINT valid_thematic_categories
      CHECK (
        thematic_categories IS NULL
        OR thematic_categories <@ ARRAY[
          'Garden Basics',
          'Plant Growth',
          'Garden Communities',
          'Ecosystems',
          'Seed to Table',
          'Food Systems',
          'Food Justice'
        ]::text[]
      )
      NOT VALID;
  END IF;
END $$;

ALTER TABLE public.lessons VALIDATE CONSTRAINT valid_thematic_categories;

-- Commit the whole apply atomically (releases the lessons lock; drops the
-- TEMP mapping table). If any statement above raised, this transaction rolls
-- back every write — snapshot INSERT, UPDATE and CHECK included.
COMMIT;

-- =====================================================
-- ROLLBACK — see sibling 20260703030000_normalize_kebab_theme_values.sql.rollback
-- (drops valid_thematic_categories FIRST, then restores both stores from
--  public.fp02_theme_normalize_rollback; the snapshot table is left in place.)
-- =====================================================
