-- =====================================================
-- Migration: pr5a_heritage_canonicalization
-- =====================================================
-- GENERATED by scripts/generate-heritage-rewrite-migration.py from
-- data/vocab/cultural-heritage.vocab.json — regenerate, don't hand-edit.
--   artifact source: docs/plans/2026-05-10-metadata-rebuild-stage1-heritage-worksheet.md
--   artifact source_commit: 9f2556d8f33375bdf0a61987ea96b7cd3fa960b8
--   artifact emitted: 2026-06-11
--
-- Description: Rewrite every live lessons.cultural_heritage value to its
-- Stage-1-locked canonical Title Case surface label (PR 5a — D4 vocabulary
-- canonicalization, heritage rehearsal). 17 non-identity rewrites:
-- 13 kebab drift literals + 4 semantic merges (Native American /
-- Indigenous/Native American / Indigenous Peoples → Indigenous;
-- African American diaspora → African American).
--
-- Mechanism notes (design doc 2026-06-11-…-pr5-canonicalization-design.md §4):
--   * Writes the cultural_heritage COLUMN only. lessons_normalize_write §J
--     mirrors the column into metadata->'culturalHeritage' in the same
--     statement (column wins on disagreement, 20260518000000).
--   * update_lesson_search_vector_trigger (UPDATE OF cultural_heritage,
--     20260521000000) regenerates search_vector row-by-row.
--   * Live rows only (retired_at IS NULL) — the 21 soft-retired imports
--     keep their archival vocabulary (user decision 2026-06-11).
--   * Idempotent: canonical labels are not in the alias list, so re-running
--     the UPDATE matches zero rows; the snapshot INSERT is ON CONFLICT
--     DO NOTHING, so re-runs never overwrite original pre-rewrite values.

-- =====================================================
-- (1) Rollback snapshot — original values of every row the rewrite touches
-- =====================================================

CREATE TABLE IF NOT EXISTS public.pr5a_heritage_rollback (
  lesson_id text PRIMARY KEY,
  cultural_heritage text[],
  metadata_culturalheritage jsonb
);

-- Service-role-only: RLS enabled with NO policies.
ALTER TABLE public.pr5a_heritage_rollback ENABLE ROW LEVEL SECURITY;

INSERT INTO public.pr5a_heritage_rollback (lesson_id, cultural_heritage, metadata_culturalheritage)
SELECT l.lesson_id, l.cultural_heritage, l.metadata->'culturalHeritage'
FROM public.lessons l
WHERE l.retired_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM unnest(l.cultural_heritage) v
    JOIN (VALUES
        ('African American diaspora', 'African American'),
        ('Indigenous Peoples', 'Indigenous'),
        ('Indigenous/Native American', 'Indigenous'),
        ('Native American', 'Indigenous'),
        ('african', 'African'),
        ('americas', 'Americas'),
        ('asian', 'Asian'),
        ('caribbean', 'Caribbean'),
        ('east-asian', 'East Asian'),
        ('eastern-european', 'Eastern European'),
        ('european', 'European'),
        ('latin-american', 'Latin American'),
        ('levantine', 'Levantine'),
        ('mediterranean', 'Mediterranean'),
        ('middle-eastern', 'Middle Eastern'),
        ('north-american', 'North American'),
        ('south-asian', 'South Asian')
    ) m(alias, canonical) ON v = m.alias
  )
ON CONFLICT (lesson_id) DO NOTHING;

-- =====================================================
-- (2) Rewrite: map aliases → canonical surface labels, dedupe preserving
--     first-occurrence order
-- =====================================================

WITH alias_map(alias, canonical) AS (
  VALUES
    ('African American diaspora', 'African American'),
    ('Indigenous Peoples', 'Indigenous'),
    ('Indigenous/Native American', 'Indigenous'),
    ('Native American', 'Indigenous'),
    ('african', 'African'),
    ('americas', 'Americas'),
    ('asian', 'Asian'),
    ('caribbean', 'Caribbean'),
    ('east-asian', 'East Asian'),
    ('eastern-european', 'Eastern European'),
    ('european', 'European'),
    ('latin-american', 'Latin American'),
    ('levantine', 'Levantine'),
    ('mediterranean', 'Mediterranean'),
    ('middle-eastern', 'Middle Eastern'),
    ('north-american', 'North American'),
    ('south-asian', 'South Asian')
)
UPDATE public.lessons l
SET cultural_heritage = (
  SELECT array_agg(val ORDER BY first_ord)
  FROM (
    SELECT COALESCE(m.canonical, u.val) AS val, min(u.ord) AS first_ord
    FROM unnest(l.cultural_heritage) WITH ORDINALITY u(val, ord)
    LEFT JOIN alias_map m ON m.alias = u.val
    GROUP BY COALESCE(m.canonical, u.val)
  ) mapped
)
WHERE l.retired_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM unnest(l.cultural_heritage) v
    JOIN alias_map m ON v = m.alias
  );

-- =====================================================
-- (3) Post-verify: no alias literal survives on any live row
--     (column AND metadata mirror)
-- =====================================================

DO $$
DECLARE
  v_aliases CONSTANT text[] := ARRAY[
        'African American diaspora', 'Indigenous Peoples', 'Indigenous/Native American', 'Native American',
        'african', 'americas', 'asian', 'caribbean',
        'east-asian', 'eastern-european', 'european', 'latin-american',
        'levantine', 'mediterranean', 'middle-eastern', 'north-american',
        'south-asian'
  ];
  v_column_rows integer;
  v_metadata_rows integer;
BEGIN
  SELECT count(*) INTO v_column_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND l.cultural_heritage && v_aliases;

  SELECT count(*) INTO v_metadata_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND jsonb_typeof(l.metadata->'culturalHeritage') = 'array'
    AND EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(l.metadata->'culturalHeritage') mv
      WHERE mv = ANY (v_aliases)
    );

  IF v_column_rows > 0 OR v_metadata_rows > 0 THEN
    RAISE EXCEPTION
      'pr5a heritage canonicalization failed post-verify: % live rows with alias in column, % in metadata mirror',
      v_column_rows, v_metadata_rows;
  END IF;
END $$;

-- =====================================================
-- ROLLBACK (keep as comments)
-- =====================================================
-- Restore is a FORWARD migration reading the snapshot table. Restoring the
-- column is sufficient: lessons_normalize_write §J re-mirrors metadata from
-- the column (column wins), and the FTS trigger refreshes search_vector
-- (UPDATE OF cultural_heritage).
--
-- UPDATE public.lessons l
-- SET cultural_heritage = r.cultural_heritage
-- FROM public.pr5a_heritage_rollback r
-- WHERE l.lesson_id = r.lesson_id;
--
-- pr5a_heritage_rollback is dropped by a cleanup migration after PR 6 ships:
-- DROP TABLE IF EXISTS public.pr5a_heritage_rollback;
