-- =====================================================
-- Migration: pr5b_concepts_canonicalization
-- =====================================================
-- GENERATED by scripts/generate-concepts-rewrite-migration.py from
-- data/vocab/academic-concepts.vocab.json — regenerate, don't hand-edit.
--   artifact source: docs/plans/2026-06-11-metadata-rebuild-stage1-concepts-worksheet-returned.md
--   artifact source_commit: f3f050f0c1f1d12f2a9e1525957025481374261e
--   artifact emitted: 2026-06-11
--
-- Description: Rewrite every live metadata->'academicConcepts' value to its
-- Stage-1-locked canonical Title Case surface label (PR 5b — D4 vocabulary
-- canonicalization, concepts at scale). 201 non-identity rewrites
-- (every stored literal is lowercase; canonical labels are Title Case, so
-- essentially every appearance rewrites — incl. 82 worksheet folds and the
-- `sorting` → "Sorting and Categorization" rename) + 7 worksheet-drop
-- literals deleted from rows (worksheet §10 contract).
--
-- Mechanism notes (design doc 2026-06-11-…-pr5-canonicalization-design.md §4):
--   * Concepts has NO flat column — the rewrite edits the jsonb key in
--     place. Shape ({Subject: [concepts]}) and subject keys are untouched
--     (no moves — §4.5); only array VALUES change.
--   * Per subject array: map literal → canonical LABEL, delete drop
--     literals, dedupe preserving first-occurrence order (folds can collide
--     with an existing co-tag). Subject keys whose arrays empty are removed;
--     if the whole object empties, the academicConcepts key is removed
--     entirely (Session-3 decision — concept-less rows lack the key).
--   * No cross-subject dedup: each subject array is rewritten independently
--     (the same canonical label may legitimately appear under two subjects).
--   * update_lesson_search_vector_trigger (UPDATE OF metadata, 20260521000000
--     + 20260523000000 helper) regenerates search_vector row-by-row.
--     lessons_normalize_write (20260518000000) also fires; its §A
--     academicIntegration.concepts rescue is inert corpus-wide and §J/§V
--     don't touch academicConcepts.
--   * Live rows only (retired_at IS NULL) — the 21 soft-retired imports
--     keep their archival vocabulary (user decision 2026-06-11).
--   * Non-array subject values pass through untouched (none exist in the
--     corpus — all 216 (subject, array) pairs verified array-shaped on TEST
--     2026-06-11; the guard mirrors 20260523000000's shape hardening).
--   * Idempotent: canonical labels are in neither the alias nor the drop
--     literal sets (generator-checked), so re-running the UPDATE matches
--     zero rows; the snapshot INSERT is ON CONFLICT DO NOTHING, so re-runs
--     never overwrite original pre-rewrite values.

-- =====================================================
-- (1) Rollback snapshot — original values of every row the rewrite touches
-- =====================================================

CREATE TABLE IF NOT EXISTS public.pr5b_concepts_rollback (
  lesson_id text PRIMARY KEY,
  metadata_academicconcepts jsonb
);

-- Service-role-only: RLS enabled with NO policies.
ALTER TABLE public.pr5b_concepts_rollback ENABLE ROW LEVEL SECURITY;

INSERT INTO public.pr5b_concepts_rollback (lesson_id, metadata_academicconcepts)
SELECT l.lesson_id, l.metadata->'academicConcepts'
FROM public.lessons l
WHERE l.retired_at IS NULL
  AND jsonb_typeof(l.metadata->'academicConcepts') = 'object'
  AND EXISTS (
    SELECT 1
    FROM jsonb_each(l.metadata->'academicConcepts') s(subj, arr)
    CROSS JOIN LATERAL jsonb_array_elements_text(
      CASE WHEN jsonb_typeof(s.arr) = 'array' THEN s.arr ELSE '[]'::jsonb END
    ) v(val)
    WHERE v.val IN (
        'Indigenous knowledge', 'Indigenous stories', 'Native American history', 'adaptation',
        'adaptations', 'advertising', 'advocacy', 'animal needs',
        'animal welfare', 'area', 'argumentation', 'argumentative writing',
        'beneficial insect identification', 'bilingual education', 'biodiversity', 'biography',
        'biography reading', 'biotic/abiotic factors', 'cardiovascular system', 'categorization',
        'cellular respiration', 'chemical reactions', 'circulatory system', 'civil rights movement',
        'climate', 'climate change', 'colonialism''s impact', 'coloring',
        'colors of plants', 'community', 'community activism', 'community building',
        'community systems', 'companion planting', 'comparative writing', 'consumers',
        'counting', 'craft activity', 'creative writing', 'cultural narratives',
        'cultural traditions', 'dance', 'data collection', 'debate',
        'decomposition', 'descriptive language', 'descriptive writing', 'design',
        'discussion', 'drawing', 'ecosystems', 'engineering',
        'environmental impact', 'environmental justice', 'environmental stewardship', 'erosion',
        'estimation', 'factory farming', 'family traditions', 'farm labor',
        'feedback systems', 'fermentation', 'figurative language', 'food marketing',
        'food memory', 'food presentation', 'food preservation', 'food processing',
        'food systems', 'food webs', 'fractions', 'garden exploration',
        'garden topics', 'general exploration', 'geography', 'germination',
        'global connections', 'graphing', 'growing cycles', 'growth patterns',
        'habitats', 'harvest', 'harvesting', 'healthy choices',
        'historical context', 'historical figures', 'history of the American West', 'holidays',
        'homeostasis', 'how-to writing', 'hydration', 'identifying plants',
        'imaginary play', 'immigration stories', 'informational text', 'informational writing',
        'instrument making', 'international food traditions', 'legumes', 'letter writing',
        'life cycles', 'literary elements', 'macromolecules', 'macronutrients',
        'map reading', 'measurement', 'mechanical energy', 'microbiome',
        'microorganisms', 'movement', 'music', 'narrative reading',
        'narrative writing', 'national and religious holidays', 'note-taking', 'novel connections',
        'nutrition', 'nutrition education', 'observation', 'opinion writing',
        'organizing ideas', 'painting', 'patterns', 'performance',
        'perimeter', 'persuasive writing', 'pests', 'phases of matter',
        'photojournalism', 'photosynthesis', 'plant ID', 'plant adaptation',
        'plant adaptations', 'plant and animal similarities', 'plant growth', 'plant identification',
        'plant needs', 'plant nutrition', 'plant parts', 'plant reproduction',
        'plant science', 'plant-based proteins', 'planting', 'poetry',
        'pollinators', 'preservation', 'problem solving', 'producers',
        'protein', 'public speaking', 'puppet making', 'puppetry',
        'ratios', 'read-aloud', 'reading', 'reading comprehension',
        'recipe reading', 'recipe scaling', 'recipe selection', 'recipe writing',
        'research', 'root vegetables', 'roots', 'scaling',
        'scientific claims', 'scientific method', 'seasonal change', 'seasonal changes',
        'seasonal cycles', 'seasonal eating', 'seasonality', 'seasons',
        'seed dispersal', 'seed starting', 'seeds', 'sensory details',
        'sensory exploration', 'sequencing', 'similes', 'simple machines',
        'slavery', 'social justice', 'social justice issues', 'soil',
        'soil science', 'song', 'sorting', 'sound',
        'spacing', 'spices', 'states of matter', 'storytelling',
        'tallying', 'taste', 'thermal energy', 'tool use',
        'trade routes', 'unit rates', 'visual arts', 'vocabulary development',
        'volume', 'voting', 'water cycles', 'weather',
        'weight', 'writing', 'writing claims', 'yeast'
    )
  )
ON CONFLICT (lesson_id) DO NOTHING;

-- =====================================================
-- (2) Rewrite: per subject array, map aliases → canonical surface labels,
--     delete drop literals, dedupe preserving first-occurrence order,
--     remove emptied subject keys / the emptied academicConcepts key
-- =====================================================

WITH alias_map(alias, canonical) AS (
  VALUES
    ('Indigenous knowledge', 'Indigenous Knowledge'),
    ('Indigenous stories', 'Cultural Narratives'),
    ('Native American history', 'Native American History'),
    ('adaptation', 'Adaptations'),
    ('adaptations', 'Adaptations'),
    ('advertising', 'Advertising'),
    ('advocacy', 'Advocacy'),
    ('animal needs', 'Animal Needs'),
    ('animal welfare', 'Animal Welfare'),
    ('area', 'Measurement'),
    ('argumentation', 'Argumentation'),
    ('argumentative writing', 'Persuasive Writing'),
    ('beneficial insect identification', 'Pollinators'),
    ('bilingual education', 'Bilingual Education'),
    ('biodiversity', 'Biodiversity'),
    ('biography', 'Reading'),
    ('biography reading', 'Reading'),
    ('biotic/abiotic factors', 'Ecosystems'),
    ('cardiovascular system', 'Circulatory System'),
    ('categorization', 'Sorting and Categorization'),
    ('cellular respiration', 'Cellular Respiration'),
    ('chemical reactions', 'Chemical Reactions'),
    ('circulatory system', 'Circulatory System'),
    ('civil rights movement', 'Civil Rights Movement'),
    ('climate', 'Climate'),
    ('climate change', 'Climate Change'),
    ('colonialism''s impact', 'Colonialism''s Impact'),
    ('coloring', 'Visual Arts'),
    ('colors of plants', 'Plant Parts'),
    ('community', 'Community Systems'),
    ('community activism', 'Advocacy'),
    ('community building', 'Community Systems'),
    ('community systems', 'Community Systems'),
    ('companion planting', 'Companion Planting'),
    ('comparative writing', 'Comparative Writing'),
    ('consumers', 'Food Webs'),
    ('counting', 'Counting'),
    ('craft activity', 'Visual Arts'),
    ('creative writing', 'Creative Writing'),
    ('cultural narratives', 'Cultural Narratives'),
    ('cultural traditions', 'Cultural Traditions'),
    ('dance', 'Movement'),
    ('data collection', 'Data Collection'),
    ('debate', 'Debate'),
    ('decomposition', 'Decomposition'),
    ('descriptive language', 'Vocabulary Development'),
    ('descriptive writing', 'Descriptive Writing'),
    ('drawing', 'Drawing'),
    ('ecosystems', 'Ecosystems'),
    ('engineering', 'Engineering'),
    ('environmental impact', 'Environmental Justice'),
    ('environmental justice', 'Environmental Justice'),
    ('environmental stewardship', 'Environmental Stewardship'),
    ('erosion', 'Soil Science'),
    ('estimation', 'Estimation'),
    ('factory farming', 'Factory Farming'),
    ('family traditions', 'Cultural Traditions'),
    ('farm labor', 'Farm Labor'),
    ('feedback systems', 'Feedback Systems'),
    ('fermentation', 'Fermentation'),
    ('figurative language', 'Figurative Language'),
    ('food marketing', 'Advertising'),
    ('food memory', 'Cultural Narratives'),
    ('food presentation', 'Food Presentation'),
    ('food preservation', 'Preservation'),
    ('food processing', 'Food Processing'),
    ('food webs', 'Food Webs'),
    ('fractions', 'Fractions'),
    ('garden exploration', 'Garden Exploration'),
    ('geography', 'Geography'),
    ('germination', 'Germination'),
    ('global connections', 'Global Connections'),
    ('graphing', 'Graphing'),
    ('growing cycles', 'Plant Growth'),
    ('growth patterns', 'Plant Growth'),
    ('habitats', 'Habitats'),
    ('harvest', 'Harvesting'),
    ('harvesting', 'Harvesting'),
    ('healthy choices', 'Healthy Choices'),
    ('historical figures', 'Historical Figures'),
    ('history of the American West', 'History of the American West'),
    ('holidays', 'Cultural Traditions'),
    ('homeostasis', 'Homeostasis'),
    ('how-to writing', 'How-to Writing'),
    ('hydration', 'Hydration'),
    ('identifying plants', 'Plant Identification'),
    ('imaginary play', 'Imaginary Play'),
    ('immigration stories', 'Immigration Stories'),
    ('informational text', 'Reading'),
    ('informational writing', 'How-to Writing'),
    ('instrument making', 'Music'),
    ('international food traditions', 'Cultural Traditions'),
    ('legumes', 'Legumes'),
    ('letter writing', 'Letter Writing'),
    ('life cycles', 'Life Cycles'),
    ('literary elements', 'Literary Elements'),
    ('macromolecules', 'Nutrition Education'),
    ('macronutrients', 'Nutrition Education'),
    ('map reading', 'Geography'),
    ('measurement', 'Measurement'),
    ('mechanical energy', 'Mechanical Energy'),
    ('microbiome', 'Microorganisms'),
    ('microorganisms', 'Microorganisms'),
    ('movement', 'Movement'),
    ('music', 'Music'),
    ('narrative reading', 'Reading'),
    ('narrative writing', 'Narrative Writing'),
    ('national and religious holidays', 'Cultural Traditions'),
    ('note-taking', 'Research'),
    ('novel connections', 'Novel Connections'),
    ('nutrition', 'Nutrition Education'),
    ('nutrition education', 'Nutrition Education'),
    ('observation', 'Observation'),
    ('opinion writing', 'Opinion Writing'),
    ('organizing ideas', 'Research'),
    ('painting', 'Visual Arts'),
    ('patterns', 'Patterns'),
    ('performance', 'Performance'),
    ('perimeter', 'Measurement'),
    ('persuasive writing', 'Persuasive Writing'),
    ('pests', 'Pests'),
    ('phases of matter', 'Phases of Matter'),
    ('photojournalism', 'Photojournalism'),
    ('photosynthesis', 'Photosynthesis'),
    ('plant ID', 'Plant Identification'),
    ('plant adaptation', 'Adaptations'),
    ('plant adaptations', 'Adaptations'),
    ('plant and animal similarities', 'Life Cycles'),
    ('plant growth', 'Plant Growth'),
    ('plant identification', 'Plant Identification'),
    ('plant needs', 'Plant Needs'),
    ('plant nutrition', 'Plant Needs'),
    ('plant parts', 'Plant Parts'),
    ('plant reproduction', 'Plant Reproduction'),
    ('plant-based proteins', 'Nutrition Education'),
    ('planting', 'Planting'),
    ('poetry', 'Poetry'),
    ('pollinators', 'Pollinators'),
    ('preservation', 'Preservation'),
    ('problem solving', 'Problem Solving'),
    ('producers', 'Food Webs'),
    ('protein', 'Nutrition Education'),
    ('public speaking', 'Public Speaking'),
    ('puppet making', 'Visual Arts'),
    ('puppetry', 'Visual Arts'),
    ('ratios', 'Ratios'),
    ('read-aloud', 'Read-Aloud'),
    ('reading', 'Reading'),
    ('reading comprehension', 'Reading'),
    ('recipe reading', 'Recipe Reading'),
    ('recipe scaling', 'Recipe Scaling'),
    ('recipe selection', 'Recipe Reading'),
    ('recipe writing', 'How-to Writing'),
    ('research', 'Research'),
    ('root vegetables', 'Root Vegetables'),
    ('roots', 'Plant Parts'),
    ('scaling', 'Recipe Scaling'),
    ('scientific claims', 'Scientific Method'),
    ('scientific method', 'Scientific Method'),
    ('seasonal change', 'Seasonality'),
    ('seasonal changes', 'Seasonality'),
    ('seasonal cycles', 'Seasonality'),
    ('seasonal eating', 'Seasonality'),
    ('seasonality', 'Seasonality'),
    ('seasons', 'Seasonality'),
    ('seed dispersal', 'Seed Dispersal'),
    ('seed starting', 'Seeds'),
    ('seeds', 'Seeds'),
    ('sensory details', 'Sensory Details'),
    ('sensory exploration', 'Sensory Exploration'),
    ('sequencing', 'Sequencing'),
    ('similes', 'Figurative Language'),
    ('simple machines', 'Engineering'),
    ('slavery', 'Slavery'),
    ('social justice', 'Social Justice Issues'),
    ('social justice issues', 'Social Justice Issues'),
    ('soil', 'Soil Science'),
    ('soil science', 'Soil Science'),
    ('song', 'Music'),
    ('sorting', 'Sorting and Categorization'),
    ('sound', 'Sound'),
    ('spacing', 'Planting'),
    ('spices', 'Spices'),
    ('states of matter', 'Phases of Matter'),
    ('storytelling', 'Storytelling'),
    ('tallying', 'Counting'),
    ('taste', 'Sensory Exploration'),
    ('thermal energy', 'Thermal Energy'),
    ('tool use', 'Tool Use'),
    ('trade routes', 'Trade Routes'),
    ('unit rates', 'Ratios'),
    ('visual arts', 'Visual Arts'),
    ('vocabulary development', 'Vocabulary Development'),
    ('volume', 'Measurement'),
    ('voting', 'Voting'),
    ('water cycles', 'Water Cycles'),
    ('weather', 'Climate'),
    ('weight', 'Measurement'),
    ('writing', 'Writing'),
    ('writing claims', 'Persuasive Writing'),
    ('yeast', 'Fermentation')
),
drop_literals(literal) AS (
  VALUES
    ('design'),
    ('discussion'),
    ('food systems'),
    ('garden topics'),
    ('general exploration'),
    ('historical context'),
    ('plant science')
)
UPDATE public.lessons l
SET metadata = (
  SELECT CASE
           WHEN agg.new_obj IS NULL THEN l.metadata - 'academicConcepts'
           ELSE jsonb_set(l.metadata, '{academicConcepts}', agg.new_obj)
         END
  FROM (
    SELECT jsonb_object_agg(per_subject.subj, per_subject.new_arr) AS new_obj
    FROM (
      SELECT s.subj,
             CASE
               WHEN jsonb_typeof(s.arr) <> 'array' THEN s.arr  -- passthrough (none in corpus)
               ELSE (
                 SELECT jsonb_agg(mapped.val ORDER BY mapped.first_ord)
                 FROM (
                   SELECT COALESCE(m.canonical, u.val) AS val, min(u.ord) AS first_ord
                   FROM jsonb_array_elements_text(s.arr) WITH ORDINALITY u(val, ord)
                   LEFT JOIN alias_map m ON m.alias = u.val
                   WHERE u.val NOT IN (SELECT literal FROM drop_literals)
                   GROUP BY COALESCE(m.canonical, u.val)
                 ) mapped
               )
             END AS new_arr
      FROM jsonb_each(l.metadata->'academicConcepts') s(subj, arr)
    ) per_subject
    WHERE per_subject.new_arr IS NOT NULL  -- removes subject keys whose arrays emptied
  ) agg
)
WHERE l.retired_at IS NULL
  AND jsonb_typeof(l.metadata->'academicConcepts') = 'object'
  AND EXISTS (
    SELECT 1
    FROM jsonb_each(l.metadata->'academicConcepts') s(subj, arr)
    CROSS JOIN LATERAL jsonb_array_elements_text(
      CASE WHEN jsonb_typeof(s.arr) = 'array' THEN s.arr ELSE '[]'::jsonb END
    ) v(val)
    WHERE v.val IN (SELECT alias FROM alias_map)
       OR v.val IN (SELECT literal FROM drop_literals)
  );

-- =====================================================
-- (3) Post-verify: no alias or drop literal survives on any live row;
--     no empty subject array; no empty academicConcepts object
-- =====================================================

DO $$
DECLARE
  v_bad_literals CONSTANT text[] := ARRAY[
        'Indigenous knowledge', 'Indigenous stories', 'Native American history', 'adaptation',
        'adaptations', 'advertising', 'advocacy', 'animal needs',
        'animal welfare', 'area', 'argumentation', 'argumentative writing',
        'beneficial insect identification', 'bilingual education', 'biodiversity', 'biography',
        'biography reading', 'biotic/abiotic factors', 'cardiovascular system', 'categorization',
        'cellular respiration', 'chemical reactions', 'circulatory system', 'civil rights movement',
        'climate', 'climate change', 'colonialism''s impact', 'coloring',
        'colors of plants', 'community', 'community activism', 'community building',
        'community systems', 'companion planting', 'comparative writing', 'consumers',
        'counting', 'craft activity', 'creative writing', 'cultural narratives',
        'cultural traditions', 'dance', 'data collection', 'debate',
        'decomposition', 'descriptive language', 'descriptive writing', 'design',
        'discussion', 'drawing', 'ecosystems', 'engineering',
        'environmental impact', 'environmental justice', 'environmental stewardship', 'erosion',
        'estimation', 'factory farming', 'family traditions', 'farm labor',
        'feedback systems', 'fermentation', 'figurative language', 'food marketing',
        'food memory', 'food presentation', 'food preservation', 'food processing',
        'food systems', 'food webs', 'fractions', 'garden exploration',
        'garden topics', 'general exploration', 'geography', 'germination',
        'global connections', 'graphing', 'growing cycles', 'growth patterns',
        'habitats', 'harvest', 'harvesting', 'healthy choices',
        'historical context', 'historical figures', 'history of the American West', 'holidays',
        'homeostasis', 'how-to writing', 'hydration', 'identifying plants',
        'imaginary play', 'immigration stories', 'informational text', 'informational writing',
        'instrument making', 'international food traditions', 'legumes', 'letter writing',
        'life cycles', 'literary elements', 'macromolecules', 'macronutrients',
        'map reading', 'measurement', 'mechanical energy', 'microbiome',
        'microorganisms', 'movement', 'music', 'narrative reading',
        'narrative writing', 'national and religious holidays', 'note-taking', 'novel connections',
        'nutrition', 'nutrition education', 'observation', 'opinion writing',
        'organizing ideas', 'painting', 'patterns', 'performance',
        'perimeter', 'persuasive writing', 'pests', 'phases of matter',
        'photojournalism', 'photosynthesis', 'plant ID', 'plant adaptation',
        'plant adaptations', 'plant and animal similarities', 'plant growth', 'plant identification',
        'plant needs', 'plant nutrition', 'plant parts', 'plant reproduction',
        'plant science', 'plant-based proteins', 'planting', 'poetry',
        'pollinators', 'preservation', 'problem solving', 'producers',
        'protein', 'public speaking', 'puppet making', 'puppetry',
        'ratios', 'read-aloud', 'reading', 'reading comprehension',
        'recipe reading', 'recipe scaling', 'recipe selection', 'recipe writing',
        'research', 'root vegetables', 'roots', 'scaling',
        'scientific claims', 'scientific method', 'seasonal change', 'seasonal changes',
        'seasonal cycles', 'seasonal eating', 'seasonality', 'seasons',
        'seed dispersal', 'seed starting', 'seeds', 'sensory details',
        'sensory exploration', 'sequencing', 'similes', 'simple machines',
        'slavery', 'social justice', 'social justice issues', 'soil',
        'soil science', 'song', 'sorting', 'sound',
        'spacing', 'spices', 'states of matter', 'storytelling',
        'tallying', 'taste', 'thermal energy', 'tool use',
        'trade routes', 'unit rates', 'visual arts', 'vocabulary development',
        'volume', 'voting', 'water cycles', 'weather',
        'weight', 'writing', 'writing claims', 'yeast'
  ];
  v_literal_rows integer;
  v_empty_array_rows integer;
  v_empty_object_rows integer;
BEGIN
  SELECT count(*) INTO v_literal_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND jsonb_typeof(l.metadata->'academicConcepts') = 'object'
    AND EXISTS (
      SELECT 1
      FROM jsonb_each(l.metadata->'academicConcepts') s(subj, arr)
      CROSS JOIN LATERAL jsonb_array_elements_text(
        CASE WHEN jsonb_typeof(s.arr) = 'array' THEN s.arr ELSE '[]'::jsonb END
      ) v(val)
      WHERE v.val = ANY (v_bad_literals)
    );

  SELECT count(*) INTO v_empty_array_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND jsonb_typeof(l.metadata->'academicConcepts') = 'object'
    AND EXISTS (
      SELECT 1
      FROM jsonb_each(l.metadata->'academicConcepts') s(subj, arr)
      WHERE s.arr = '[]'::jsonb
    );

  SELECT count(*) INTO v_empty_object_rows
  FROM public.lessons l
  WHERE l.retired_at IS NULL
    AND l.metadata->'academicConcepts' = '{}'::jsonb;

  IF v_literal_rows > 0 OR v_empty_array_rows > 0 OR v_empty_object_rows > 0 THEN
    RAISE EXCEPTION
      'pr5b concepts canonicalization failed post-verify: % live rows with surviving alias/drop literal, % with empty subject array, % with empty academicConcepts object',
      v_literal_rows, v_empty_array_rows, v_empty_object_rows;
  END IF;
END $$;

-- =====================================================
-- ROLLBACK (keep as comments)
-- =====================================================
-- Restore is a FORWARD migration reading the snapshot table. jsonb_set
-- re-adds the academicConcepts key for rows whose object emptied (its
-- create-if-missing default is true); the FTS trigger refreshes
-- search_vector (UPDATE OF metadata). lessons_normalize_write's §A rescue
-- stays inert (academicIntegration.concepts is empty corpus-wide).
--
-- UPDATE public.lessons l
-- SET metadata = jsonb_set(l.metadata, '{academicConcepts}', r.metadata_academicconcepts)
-- FROM public.pr5b_concepts_rollback r
-- WHERE l.lesson_id = r.lesson_id;
--
-- pr5b_concepts_rollback is dropped by a cleanup migration after PR 6 ships:
-- DROP TABLE IF EXISTS public.pr5b_concepts_rollback;
