-- =====================================================
-- Migration: 20260616000000_heritage_recursive_expansion.sql
-- =====================================================
-- Description:
--   PR C1.2 — Heritage filter rebuild (Option B, filter-first).
--
--   Rebuilds the cultural-heritage filter mechanism so that selecting a parent
--   region recursively expands to ALL transitive descendants (full subtree),
--   sourced from the single source of truth data/vocab/cultural-heritage.vocab.json.
--
--   Two coordinated changes, in ONE idempotent migration:
--     1. Recreate `cultural_heritage_hierarchy` with the new normalized shape
--        (key, label, parent_key) and reseed with the full 71-row vocab tree
--        (top + sub + internal tiers — internal nodes are hidden in the UI but
--        MUST live here so the recursive walk can match them).
--     2. Rewrite `expand_cultural_heritage(text[]) RETURNS text[]` as a
--        WITH RECURSIVE walk that, given the alias output (a mix of slugs and
--        Title-Case labels), returns the matched nodes PLUS all transitive
--        descendants, resolved to Title-Case LABELS for the `&&` overlap in
--        search_lessons (the column stores labels — returning slugs would match
--        NOTHING; this is the central footgun this rebuild fixes).
--
--   The function signature is preserved exactly (cultures text[] -> text[],
--   plain LANGUAGE plpgsql / VOLATILE / SECURITY INVOKER), so search_lessons
--   and _alias_cultural_heritage need NO change — search_lessons keeps calling
--   expand_cultural_heritage(_alias_cultural_heritage(filter_cultures)) and the
--   `l.cultural_heritage && expanded_cultures` overlap keeps comparing labels.
--
--   NO lesson-data writes. Backward-compatible on current full-chain corpus
--   (keystone-proven superset: counts can only grow, never shrink).
--
--   Pre-flight (PR C1.2): confirmed NO other DB object depends on the old
--   (id, parent, children) columns — 0 views, 0 FKs, 0 triggers; only
--   expand_cultural_heritage reads the table, and it is rewritten here in the
--   same migration. The 4 RLS policies + grants from the production baseline
--   are recreated below so the public read path keeps working.
--
-- Source of truth: data/vocab/cultural-heritage.vocab.json
-- Seed fragment generated by: scripts/heritage/generate-heritage-hierarchy.ts (C1.1)
--
-- =====================================================
-- CHANGES
-- =====================================================

-- ---------------------------------------------------------------------------
-- 1. Recreate cultural_heritage_hierarchy with the new (key, label, parent_key)
--    shape. The only reader (expand_cultural_heritage) is rewritten below in
--    the same migration, so dropping + recreating is safe. CASCADE also drops
--    the now-orphaned id sequence (it was OWNED BY the old id column); we drop
--    it explicitly too for idempotent re-runs.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS public.cultural_heritage_hierarchy CASCADE;
DROP SEQUENCE IF EXISTS public.cultural_heritage_hierarchy_id_seq CASCADE;

CREATE TABLE public.cultural_heritage_hierarchy (
    key        text PRIMARY KEY,
    label      text NOT NULL,
    parent_key text REFERENCES public.cultural_heritage_hierarchy(key)
);

ALTER TABLE public.cultural_heritage_hierarchy OWNER TO postgres;

COMMENT ON TABLE public.cultural_heritage_hierarchy IS
  'Cultural heritage hierarchy tree (key, label, parent_key). Roots have NULL parent_key. '
  'Single source of truth: data/vocab/cultural-heritage.vocab.json. Consumed only by '
  'expand_cultural_heritage() for recursive parent->descendant filter expansion.';

-- RLS: same posture as the production baseline (public read, admin write).
ALTER TABLE public.cultural_heritage_hierarchy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view cultural hierarchy"
  ON public.cultural_heritage_hierarchy
  FOR SELECT USING (true);

CREATE POLICY "Admins can insert hierarchy"
  ON public.cultural_heritage_hierarchy
  FOR INSERT WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Admins can update hierarchy"
  ON public.cultural_heritage_hierarchy
  FOR UPDATE USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Admins can delete hierarchy"
  ON public.cultural_heritage_hierarchy
  FOR DELETE USING (public.is_admin(auth.uid()));

-- Grants: match the production baseline (anon/authenticated/service_role).
GRANT ALL ON TABLE public.cultural_heritage_hierarchy TO anon;
GRANT ALL ON TABLE public.cultural_heritage_hierarchy TO authenticated;
GRANT ALL ON TABLE public.cultural_heritage_hierarchy TO service_role;

-- ---------------------------------------------------------------------------
-- 2. Reseed the full vocab tree (71 rows: top + sub + internal tiers).
--    Rows are emitted by the C1.1 generator
--    (scripts/heritage/generate-heritage-hierarchy.ts) from
--    data/vocab/cultural-heritage.vocab.json in TOPOLOGICAL order — depth ASC
--    (roots first, every parent row before its children), then frequency DESC,
--    then key ASC within each depth band — and are copied here VERBATIM from
--    scripts/heritage/artifacts/heritage-hierarchy-seed.sql (the generator is
--    the single source of truth; the drift-guard test keeps the two in sync).
--    NOTE: row order is not required for FK satisfaction — this is a SINGLE
--    multi-row INSERT, and PostgreSQL checks the self-referential parent_key FK
--    at statement-end (after all 71 rows exist), so any permutation would also
--    satisfy it. Topological order is used purely for readability and
--    robustness (safe even if the INSERT were ever split into statements).
-- ---------------------------------------------------------------------------
INSERT INTO public.cultural_heritage_hierarchy (key, label, parent_key) VALUES
  ('americas', 'Americas', NULL),
  ('asian', 'Asian', NULL),
  ('indigenous-and-diaspora', 'Indigenous and Diaspora', NULL),
  ('european', 'European', NULL),
  ('african', 'African', NULL),
  ('middle-eastern', 'Middle Eastern', NULL),
  ('north-american', 'North American', 'americas'),
  ('latin-american', 'Latin American', 'americas'),
  ('mediterranean', 'Mediterranean', 'european'),
  ('east-asian', 'East Asian', 'asian'),
  ('african-american', 'African American', 'indigenous-and-diaspora'),
  ('indigenous', 'Indigenous', 'indigenous-and-diaspora'),
  ('caribbean', 'Caribbean', 'americas'),
  ('south-asian', 'South Asian', 'asian'),
  ('west-african', 'West African', 'african'),
  ('levantine', 'Levantine', 'middle-eastern'),
  ('southeast-asian', 'Southeast Asian', 'asian'),
  ('central-asian', 'Central Asian', 'asian'),
  ('eastern-european', 'Eastern European', 'european'),
  ('yemeni', 'Yemeni', 'middle-eastern'),
  ('irish', 'Irish', 'european'),
  ('north-african', 'North African', 'african'),
  ('central-american', 'Central American', 'americas'),
  ('east-african', 'East African', 'african'),
  ('israeli', 'Israeli', 'middle-eastern'),
  ('persian', 'Persian', 'middle-eastern'),
  ('south-american', 'South American', 'americas'),
  ('cajun-creole', 'Cajun/Creole', 'indigenous-and-diaspora'),
  ('french', 'French', 'european'),
  ('mexican', 'Mexican', 'latin-american'),
  ('italian', 'Italian', 'mediterranean'),
  ('chinese', 'Chinese', 'east-asian'),
  ('japanese', 'Japanese', 'east-asian'),
  ('indian', 'Indian', 'south-asian'),
  ('lenape', 'Lenape', 'indigenous'),
  ('spanish', 'Spanish', 'mediterranean'),
  ('pakistani', 'Pakistani', 'south-asian'),
  ('puerto-rican', 'Puerto Rican', 'latin-american'),
  ('uzbek', 'Uzbek', 'central-asian'),
  ('haudenosaunee', 'Haudenosaunee', 'indigenous'),
  ('korean', 'Korean', 'east-asian'),
  ('ukrainian', 'Ukrainian', 'eastern-european'),
  ('cuban', 'Cuban', 'caribbean'),
  ('egyptian', 'Egyptian', 'north-african'),
  ('greek', 'Greek', 'mediterranean'),
  ('honduran', 'Honduran', 'latin-american'),
  ('jamaican', 'Jamaican', 'caribbean'),
  ('kenyan', 'Kenyan', 'east-african'),
  ('nigerian', 'Nigerian', 'west-african'),
  ('peruvian', 'Peruvian', 'latin-american'),
  ('salvadoran', 'Salvadoran', 'latin-american'),
  ('vietnamese', 'Vietnamese', 'southeast-asian'),
  ('brazilian', 'Brazilian', 'latin-american'),
  ('ecuadorian', 'Ecuadorian', 'latin-american'),
  ('ethiopian', 'Ethiopian', 'east-african'),
  ('guyanese', 'Guyanese', 'latin-american'),
  ('malaysian', 'Malaysian', 'southeast-asian'),
  ('moroccan', 'Moroccan', 'north-african'),
  ('palestinian', 'Palestinian', 'levantine'),
  ('russian', 'Russian', 'eastern-european'),
  ('southern-united-states', 'Southern United States', 'north-american'),
  ('sri-lankan', 'Sri Lankan', 'south-asian'),
  ('taiwanese', 'Taiwanese', 'east-asian'),
  ('black-culinary-history', 'Black culinary history', 'african-american'),
  ('dominican', 'Dominican', 'latin-american'),
  ('jordanian', 'Jordanian', 'levantine'),
  ('lebanese', 'Lebanese', 'levantine'),
  ('polish', 'Polish', 'eastern-european'),
  ('soul-food', 'Soul Food', 'african-american'),
  ('syrian', 'Syrian', 'levantine'),
  ('three-sisters-traditions', 'Three Sisters traditions', 'indigenous');

-- ---------------------------------------------------------------------------
-- 3. Rewrite expand_cultural_heritage as a WITH RECURSIVE walk.
--
--    CONTRACT (the footgun lives here):
--    - Input `cultures` is the output of _alias_cultural_heritage: a mix of
--      slugs (keys) and Title-Case labels. For the 18 known UI slugs the alias
--      emits [slug, label]; unknown slugs (e.g. 'african-american') pass through
--      slug-only.
--    - Seed the recursion from rows where key = ANY(input) OR label = ANY(input)
--      so BOTH slug-form and label-form inputs resolve to the canonical node.
--    - Recurse over parent_key to collect the seed nodes PLUS all transitive
--      descendants (full subtree, not one tier).
--    - Return the set of LABELS (Title-Case) for all reachable nodes, because
--      search_lessons compares the result against the label-stored
--      lessons.cultural_heritage column via `&&`. Returning slugs would match
--      nothing.
--    - Defensively UNION in any raw input value not found in the table, so
--      today's pass-through behavior (unknown values still flow to `&&`) is
--      preserved. Return DISTINCT.
--
--    Signature, language, volatility (VOLATILE), and security (INVOKER) are
--    preserved exactly so search_lessons needs no change.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.expand_cultural_heritage(cultures text[])
 RETURNS text[]
 LANGUAGE plpgsql
AS $function$
DECLARE
    result TEXT[];
BEGIN
    IF cultures IS NULL OR array_length(cultures, 1) IS NULL THEN
        RETURN cultures;
    END IF;

    WITH RECURSIVE
    -- Seed: every node whose key OR label appears in the (aliased) input.
    seed AS (
        SELECT h.key, h.label
        FROM public.cultural_heritage_hierarchy h
        WHERE h.key = ANY(cultures) OR h.label = ANY(cultures)
    ),
    -- Walk down parent_key to gather the seed nodes + all transitive descendants.
    subtree AS (
        SELECT s.key, s.label
        FROM seed s
        UNION
        SELECT child.key, child.label
        FROM public.cultural_heritage_hierarchy child
        JOIN subtree st ON child.parent_key = st.key
    )
    SELECT ARRAY(
        SELECT DISTINCT v FROM (
            -- Resolved subtree, returned as LABELS for the `&&` overlap.
            SELECT label AS v FROM subtree
            UNION
            -- Defensive pass-through: keep any raw input not found in the table
            -- (preserves today's behavior for values the tree doesn't know).
            SELECT raw AS v
            FROM unnest(cultures) AS raw
            WHERE NOT EXISTS (
                SELECT 1 FROM public.cultural_heritage_hierarchy h
                WHERE h.key = raw OR h.label = raw
            )
        ) AS all_values
    )
    INTO result;

    RETURN result;
END;
$function$;

-- Grants on the function were not separately set in the baseline beyond the
-- default; preserve as-is (CREATE OR REPLACE retains existing grants).

-- =====================================================
-- ROLLBACK (keep as comments)
-- =====================================================
-- This migration is not auto-reversible (it changes the table shape and reseeds).
-- To restore the prior one-tier behavior, re-apply the table + function defs
-- captured in scripts/heritage/artifacts/heritage-filter-baseline.json
-- (the (id, parent, children) shape + the non-recursive FOR-loop function).
